// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package coadb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoaSegmentDefinition struct {
	SegmentDefinitionID pgtype.UUID
	ScopeID             pgtype.UUID
	SegmentType         string
	Code                string
	Name                string
	Status              string
	EffectiveFrom       pgtype.Date
	EffectiveTo         pgtype.Date
	AggregateVersion    int64
	RevisionNumber      int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	LastAuditReference  pgtype.UUID
}

type CoaSegmentDefinitionRevision struct {
	SegmentDefinitionID pgtype.UUID
	RevisionNumber      int64
	AggregateVersion    int64
	Snapshot            []byte
	EffectiveFrom       pgtype.Date
	EffectiveTo         pgtype.Date
	CreatedAt           pgtype.Timestamptz
}
