// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package coadb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoaSegmentChangeRequest struct {
	SegmentChangeRequestID       pgtype.UUID
	ScopeID                      pgtype.UUID
	ChangeType                   string
	SubjectID                    pgtype.UUID
	SubjectVersion               int64
	RequestedEffectiveDate       pgtype.Date
	ApprovalRequestID            pgtype.UUID
	ApprovalStatus               string
	ApplicationStatus            string
	ValidationOutcome            string
	ConflictCode                 pgtype.Text
	RejectionReason              pgtype.Text
	NextAction                   string
	ProposedChange               []byte
	SubjectFingerprint           string
	ProposedFingerprint          string
	AggregateVersion             int64
	RevisionNumber               int64
	CreatedBy                    pgtype.UUID
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
	LastAuditReference           pgtype.UUID
	ApprovalDecisionID           pgtype.UUID
	ApprovalPolicyVersion        pgtype.Text
	ApprovalDecisionVersion      pgtype.Int8
	ApprovalSubjectVersion       pgtype.Int8
	ApprovalCandidateFingerprint pgtype.Text
	ApprovalApproverUserID       pgtype.UUID
	ApprovalDecidedAt            pgtype.Timestamptz
	ApprovalAppliedAt            pgtype.Timestamptz
	AppliedSubjectVersion        pgtype.Int8
	ResultingSubjectVersion      pgtype.Int8
	DecisionFingerprint          pgtype.Text
}

type CoaSegmentDefinition struct {
	SegmentDefinitionID pgtype.UUID
	ScopeID             pgtype.UUID
	SegmentType         string
	Code                string
	Name                string
	Status              string
	EffectiveFrom       pgtype.Date
	EffectiveTo         pgtype.Date
	AggregateVersion    int64
	RevisionNumber      int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	LastAuditReference  pgtype.UUID
}

type CoaSegmentDefinitionRevision struct {
	SegmentDefinitionID pgtype.UUID
	RevisionNumber      int64
	AggregateVersion    int64
	Snapshot            []byte
	EffectiveFrom       pgtype.Date
	EffectiveTo         pgtype.Date
	CreatedAt           pgtype.Timestamptz
}

type CoaSegmentValue struct {
	SegmentValueID      pgtype.UUID
	SegmentDefinitionID pgtype.UUID
	Value               string
	Description         string
	Status              string
	EffectiveFrom       pgtype.Date
	EffectiveTo         pgtype.Date
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}
