// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segment_change_request.sql

package coadb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSegmentChangeRequest = `-- name: GetSegmentChangeRequest :one
SELECT segment_change_request_id, scope_id, change_type, subject_id, subject_version,
       requested_effective_date, approval_request_id, approval_status, application_status,
       validation_outcome, conflict_code, rejection_reason, next_action, proposed_change,
       subject_fingerprint, proposed_fingerprint, aggregate_version, revision_number,
       created_by, created_at, updated_at, last_audit_reference
FROM coa.segment_change_request
WHERE segment_change_request_id = $1
`

func (q *Queries) GetSegmentChangeRequest(ctx context.Context, segmentChangeRequestID pgtype.UUID) (CoaSegmentChangeRequest, error) {
	row := q.db.QueryRow(ctx, getSegmentChangeRequest, segmentChangeRequestID)
	var i CoaSegmentChangeRequest
	err := row.Scan(
		&i.SegmentChangeRequestID,
		&i.ScopeID,
		&i.ChangeType,
		&i.SubjectID,
		&i.SubjectVersion,
		&i.RequestedEffectiveDate,
		&i.ApprovalRequestID,
		&i.ApprovalStatus,
		&i.ApplicationStatus,
		&i.ValidationOutcome,
		&i.ConflictCode,
		&i.RejectionReason,
		&i.NextAction,
		&i.ProposedChange,
		&i.SubjectFingerprint,
		&i.ProposedFingerprint,
		&i.AggregateVersion,
		&i.RevisionNumber,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAuditReference,
	)
	return i, err
}

const listSegmentChangeRequests = `-- name: ListSegmentChangeRequests :many
SELECT segment_change_request_id, scope_id, change_type, subject_id, subject_version,
       requested_effective_date, approval_request_id, approval_status, application_status,
       validation_outcome, conflict_code, rejection_reason, next_action, proposed_change,
       subject_fingerprint, proposed_fingerprint, aggregate_version, revision_number,
       created_by, created_at, updated_at, last_audit_reference
FROM coa.segment_change_request
WHERE ($1::uuid IS NULL OR scope_id = $1::uuid)
ORDER BY requested_effective_date, segment_change_request_id
`

func (q *Queries) ListSegmentChangeRequests(ctx context.Context, scopeID pgtype.UUID) ([]CoaSegmentChangeRequest, error) {
	rows, err := q.db.Query(ctx, listSegmentChangeRequests, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoaSegmentChangeRequest
	for rows.Next() {
		var i CoaSegmentChangeRequest
		if err := rows.Scan(
			&i.SegmentChangeRequestID,
			&i.ScopeID,
			&i.ChangeType,
			&i.SubjectID,
			&i.SubjectVersion,
			&i.RequestedEffectiveDate,
			&i.ApprovalRequestID,
			&i.ApprovalStatus,
			&i.ApplicationStatus,
			&i.ValidationOutcome,
			&i.ConflictCode,
			&i.RejectionReason,
			&i.NextAction,
			&i.ProposedChange,
			&i.SubjectFingerprint,
			&i.ProposedFingerprint,
			&i.AggregateVersion,
			&i.RevisionNumber,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAuditReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
