// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segment_value.sql

package coadb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listSegmentValueRows = `-- name: ListSegmentValueRows :many
SELECT segment_value_id, segment_definition_id, value, description, status,
       effective_from, effective_to, created_at, updated_at
FROM coa.segment_value
WHERE segment_definition_id = $1
ORDER BY value, effective_from, segment_value_id
`

func (q *Queries) ListSegmentValueRows(ctx context.Context, segmentDefinitionID pgtype.UUID) ([]CoaSegmentValue, error) {
	rows, err := q.db.Query(ctx, listSegmentValueRows, segmentDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoaSegmentValue
	for rows.Next() {
		var i CoaSegmentValue
		if err := rows.Scan(
			&i.SegmentValueID,
			&i.SegmentDefinitionID,
			&i.Value,
			&i.Description,
			&i.Status,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
