// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segment_definition.sql

package coadb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSegmentDefinitionRoot = `-- name: GetSegmentDefinitionRoot :one
SELECT segment_definition_id, scope_id, segment_type, code, name, status,
       effective_from, effective_to, aggregate_version, revision_number,
       created_at, updated_at, last_audit_reference
FROM coa.segment_definition
WHERE segment_definition_id = $1
`

func (q *Queries) GetSegmentDefinitionRoot(ctx context.Context, segmentDefinitionID pgtype.UUID) (CoaSegmentDefinition, error) {
	row := q.db.QueryRow(ctx, getSegmentDefinitionRoot, segmentDefinitionID)
	var i CoaSegmentDefinition
	err := row.Scan(
		&i.SegmentDefinitionID,
		&i.ScopeID,
		&i.SegmentType,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.AggregateVersion,
		&i.RevisionNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAuditReference,
	)
	return i, err
}

const listSegmentDefinitionRoots = `-- name: ListSegmentDefinitionRoots :many
SELECT segment_definition_id, scope_id, segment_type, code, name, status,
       effective_from, effective_to, aggregate_version, revision_number,
       created_at, updated_at, last_audit_reference
FROM coa.segment_definition
WHERE ($1::uuid IS NULL OR scope_id = $1::uuid)
ORDER BY segment_definition_id
`

func (q *Queries) ListSegmentDefinitionRoots(ctx context.Context, scopeID pgtype.UUID) ([]CoaSegmentDefinition, error) {
	rows, err := q.db.Query(ctx, listSegmentDefinitionRoots, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoaSegmentDefinition
	for rows.Next() {
		var i CoaSegmentDefinition
		if err := rows.Scan(
			&i.SegmentDefinitionID,
			&i.ScopeID,
			&i.SegmentType,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.AggregateVersion,
			&i.RevisionNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAuditReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
