# yaml-language-server: $schema=https://raw.githubusercontent.com/ogen-go/ogen/main/schemas/ogen.jsonschema.json

generator:
  features:
    disable:
      - "paths/client"
      - "webhooks/client"
      - "ogen/otel"
