// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chart_account.sql

package gldb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountRecord = `-- name: GetAccountRecord :one
SELECT account_id, accounting_scope_id, chart_of_accounts_id, account_code,
       account_name, account_type, normal_balance, lifecycle_status,
       restrictions, currency_policy, reporting_mappings, effective_from,
       effective_to, approval_reference, aggregate_version, revision_number,
       created_at, updated_at, last_audit_reference
FROM gl.account
WHERE account_id = $1
`

func (q *Queries) GetAccountRecord(ctx context.Context, accountID pgtype.UUID) (GlAccount, error) {
	row := q.db.QueryRow(ctx, getAccountRecord, accountID)
	var i GlAccount
	err := row.Scan(
		&i.AccountID,
		&i.AccountingScopeID,
		&i.ChartOfAccountsID,
		&i.AccountCode,
		&i.AccountName,
		&i.AccountType,
		&i.NormalBalance,
		&i.LifecycleStatus,
		&i.Restrictions,
		&i.CurrencyPolicy,
		&i.ReportingMappings,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.ApprovalReference,
		&i.AggregateVersion,
		&i.RevisionNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAuditReference,
	)
	return i, err
}

const getChartOfAccountsRecord = `-- name: GetChartOfAccountsRecord :one
SELECT chart_of_accounts_id, accounting_scope_id, ledger_id, account_code_policy,
       lifecycle_status, effective_from, effective_to, approval_reference,
       aggregate_version, revision_number, created_at, updated_at, last_audit_reference
FROM gl.chart_of_accounts
WHERE chart_of_accounts_id = $1
`

func (q *Queries) GetChartOfAccountsRecord(ctx context.Context, chartOfAccountsID pgtype.UUID) (GlChartOfAccount, error) {
	row := q.db.QueryRow(ctx, getChartOfAccountsRecord, chartOfAccountsID)
	var i GlChartOfAccount
	err := row.Scan(
		&i.ChartOfAccountsID,
		&i.AccountingScopeID,
		&i.LedgerID,
		&i.AccountCodePolicy,
		&i.LifecycleStatus,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.ApprovalReference,
		&i.AggregateVersion,
		&i.RevisionNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAuditReference,
	)
	return i, err
}

const listAccountIDs = `-- name: ListAccountIDs :many
SELECT account_id
FROM gl.account
WHERE ($1::uuid IS NULL OR accounting_scope_id = $1)
ORDER BY account_id
`

func (q *Queries) ListAccountIDs(ctx context.Context, dollar_1 pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAccountIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var account_id pgtype.UUID
		if err := rows.Scan(&account_id); err != nil {
			return nil, err
		}
		items = append(items, account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChartOfAccountsIDs = `-- name: ListChartOfAccountsIDs :many
SELECT chart_of_accounts_id
FROM gl.chart_of_accounts
WHERE ($1::uuid IS NULL OR accounting_scope_id = $1)
ORDER BY chart_of_accounts_id
`

func (q *Queries) ListChartOfAccountsIDs(ctx context.Context, dollar_1 pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listChartOfAccountsIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var chart_of_accounts_id pgtype.UUID
		if err := rows.Scan(&chart_of_accounts_id); err != nil {
			return nil, err
		}
		items = append(items, chart_of_accounts_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
