// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: configuration.sql

package gldb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountingBookRoot = `-- name: GetAccountingBookRoot :one
SELECT accounting_book_id, accounting_scope_id, ledger_id, book_type,
       accounting_basis, posting_policy_version, lifecycle_status,
       effective_from, effective_to, approval_reference,
       aggregate_version, revision_number, created_at, updated_at,
       last_audit_reference
FROM gl.accounting_book
WHERE accounting_book_id = $1
`

func (q *Queries) GetAccountingBookRoot(ctx context.Context, accountingBookID pgtype.UUID) (GlAccountingBook, error) {
	row := q.db.QueryRow(ctx, getAccountingBookRoot, accountingBookID)
	var i GlAccountingBook
	err := row.Scan(
		&i.AccountingBookID,
		&i.AccountingScopeID,
		&i.LedgerID,
		&i.BookType,
		&i.AccountingBasis,
		&i.PostingPolicyVersion,
		&i.LifecycleStatus,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.ApprovalReference,
		&i.AggregateVersion,
		&i.RevisionNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAuditReference,
	)
	return i, err
}

const getLedgerRoot = `-- name: GetLedgerRoot :one
SELECT ledger_id, accounting_scope_id, legal_entity_id, ledger_type,
       functional_currency, fiscal_calendar_id, lifecycle_status,
       effective_from, effective_to, approval_reference,
       aggregate_version, revision_number, created_at, updated_at,
       last_audit_reference
FROM gl.ledger
WHERE ledger_id = $1
`

func (q *Queries) GetLedgerRoot(ctx context.Context, ledgerID pgtype.UUID) (GlLedger, error) {
	row := q.db.QueryRow(ctx, getLedgerRoot, ledgerID)
	var i GlLedger
	err := row.Scan(
		&i.LedgerID,
		&i.AccountingScopeID,
		&i.LegalEntityID,
		&i.LedgerType,
		&i.FunctionalCurrency,
		&i.FiscalCalendarID,
		&i.LifecycleStatus,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.ApprovalReference,
		&i.AggregateVersion,
		&i.RevisionNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAuditReference,
	)
	return i, err
}

const listAccountingBookRoots = `-- name: ListAccountingBookRoots :many
SELECT accounting_book_id, accounting_scope_id, ledger_id, book_type,
       accounting_basis, posting_policy_version, lifecycle_status,
       effective_from, effective_to, approval_reference,
       aggregate_version, revision_number, created_at, updated_at,
       last_audit_reference
FROM gl.accounting_book
WHERE ($1::uuid IS NULL OR accounting_scope_id = $1::uuid)
ORDER BY accounting_book_id
`

func (q *Queries) ListAccountingBookRoots(ctx context.Context, accountingScopeID pgtype.UUID) ([]GlAccountingBook, error) {
	rows, err := q.db.Query(ctx, listAccountingBookRoots, accountingScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlAccountingBook
	for rows.Next() {
		var i GlAccountingBook
		if err := rows.Scan(
			&i.AccountingBookID,
			&i.AccountingScopeID,
			&i.LedgerID,
			&i.BookType,
			&i.AccountingBasis,
			&i.PostingPolicyVersion,
			&i.LifecycleStatus,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.ApprovalReference,
			&i.AggregateVersion,
			&i.RevisionNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAuditReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerRoots = `-- name: ListLedgerRoots :many
SELECT ledger_id, accounting_scope_id, legal_entity_id, ledger_type,
       functional_currency, fiscal_calendar_id, lifecycle_status,
       effective_from, effective_to, approval_reference,
       aggregate_version, revision_number, created_at, updated_at,
       last_audit_reference
FROM gl.ledger
WHERE ($1::uuid IS NULL OR accounting_scope_id = $1::uuid)
ORDER BY ledger_id
`

func (q *Queries) ListLedgerRoots(ctx context.Context, accountingScopeID pgtype.UUID) ([]GlLedger, error) {
	rows, err := q.db.Query(ctx, listLedgerRoots, accountingScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlLedger
	for rows.Next() {
		var i GlLedger
		if err := rows.Scan(
			&i.LedgerID,
			&i.AccountingScopeID,
			&i.LegalEntityID,
			&i.LedgerType,
			&i.FunctionalCurrency,
			&i.FiscalCalendarID,
			&i.LifecycleStatus,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.ApprovalReference,
			&i.AggregateVersion,
			&i.RevisionNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAuditReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
