// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gldb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GlAccountingBook struct {
	AccountingBookID     pgtype.UUID
	AccountingScopeID    pgtype.UUID
	LedgerID             pgtype.UUID
	BookType             string
	AccountingBasis      string
	PostingPolicyVersion string
	LifecycleStatus      string
	EffectiveFrom        pgtype.Date
	EffectiveTo          pgtype.Date
	ApprovalReference    []byte
	AggregateVersion     int64
	RevisionNumber       int64
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	LastAuditReference   pgtype.UUID
}

type GlAccountingBookRevision struct {
	AccountingBookID pgtype.UUID
	RevisionNumber   int64
	AggregateVersion int64
	Snapshot         []byte
	EffectiveFrom    pgtype.Date
	EffectiveTo      pgtype.Date
	CreatedAt        pgtype.Timestamptz
}

type GlLedger struct {
	LedgerID           pgtype.UUID
	AccountingScopeID  pgtype.UUID
	LegalEntityID      pgtype.UUID
	LedgerType         string
	FunctionalCurrency string
	FiscalCalendarID   pgtype.UUID
	LifecycleStatus    string
	EffectiveFrom      pgtype.Date
	EffectiveTo        pgtype.Date
	ApprovalReference  []byte
	AggregateVersion   int64
	RevisionNumber     int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastAuditReference pgtype.UUID
}

type GlLedgerRevision struct {
	LedgerID         pgtype.UUID
	RevisionNumber   int64
	AggregateVersion int64
	Snapshot         []byte
	EffectiveFrom    pgtype.Date
	EffectiveTo      pgtype.Date
	CreatedAt        pgtype.Timestamptz
}
