// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gldb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GlAccount struct {
	AccountID          pgtype.UUID
	AccountingScopeID  pgtype.UUID
	ChartOfAccountsID  pgtype.UUID
	AccountCode        string
	AccountName        string
	AccountType        string
	NormalBalance      string
	LifecycleStatus    string
	Restrictions       []byte
	CurrencyPolicy     string
	ReportingMappings  []byte
	EffectiveFrom      pgtype.Date
	EffectiveTo        pgtype.Date
	ApprovalReference  []byte
	AggregateVersion   int64
	RevisionNumber     int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastAuditReference pgtype.UUID
}

type GlAccountRevision struct {
	AccountID        pgtype.UUID
	RevisionNumber   int64
	AggregateVersion int64
	Snapshot         []byte
	EffectiveFrom    pgtype.Date
	EffectiveTo      pgtype.Date
	CreatedAt        pgtype.Timestamptz
}

type GlAccountingBook struct {
	AccountingBookID     pgtype.UUID
	AccountingScopeID    pgtype.UUID
	LedgerID             pgtype.UUID
	BookType             string
	AccountingBasis      string
	PostingPolicyVersion string
	LifecycleStatus      string
	EffectiveFrom        pgtype.Date
	EffectiveTo          pgtype.Date
	ApprovalReference    []byte
	AggregateVersion     int64
	RevisionNumber       int64
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	LastAuditReference   pgtype.UUID
}

type GlAccountingBookRevision struct {
	AccountingBookID pgtype.UUID
	RevisionNumber   int64
	AggregateVersion int64
	Snapshot         []byte
	EffectiveFrom    pgtype.Date
	EffectiveTo      pgtype.Date
	CreatedAt        pgtype.Timestamptz
}

type GlChartOfAccount struct {
	ChartOfAccountsID  pgtype.UUID
	AccountingScopeID  pgtype.UUID
	LedgerID           pgtype.UUID
	AccountCodePolicy  string
	LifecycleStatus    string
	EffectiveFrom      pgtype.Date
	EffectiveTo        pgtype.Date
	ApprovalReference  []byte
	AggregateVersion   int64
	RevisionNumber     int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastAuditReference pgtype.UUID
}

type GlChartOfAccountsRevision struct {
	ChartOfAccountsID pgtype.UUID
	RevisionNumber    int64
	AggregateVersion  int64
	Snapshot          []byte
	EffectiveFrom     pgtype.Date
	EffectiveTo       pgtype.Date
	CreatedAt         pgtype.Timestamptz
}

type GlJournalEntry struct {
	JournalEntryID             pgtype.UUID
	JournalNumber              string
	AccountingScopeID          pgtype.UUID
	TenantID                   pgtype.UUID
	LegalEntityID              pgtype.UUID
	LedgerID                   pgtype.UUID
	AccountingBookID           pgtype.UUID
	FunctionalCurrency         string
	SourceContext              string
	SourceAggregateType        string
	SourceAggregateID          pgtype.UUID
	SourceVersion              int64
	RequestID                  pgtype.UUID
	IdempotencyKey             string
	RequestFingerprint         string
	PostingDate                pgtype.Date
	FiscalPeriodID             pgtype.UUID
	PeriodStateVersion         int64
	PostingGateVersion         int64
	PostingPurpose             string
	AdjustmentPeriodIndicator  bool
	PostingAuthorizationID     pgtype.UUID
	CloseRunID                 pgtype.UUID
	ReopenRequestID            pgtype.UUID
	OperationalReopenRequestID pgtype.UUID
	ControlAuthorityEpoch      pgtype.Int8
	TransactionCurrency        string
	ConversionEvidence         []byte
	Description                string
	LifecycleStatus            string
	ApprovalReference          []byte
	AggregateVersion           int64
	LedgerPosition             pgtype.Int8
	AuditReference             pgtype.UUID
	CorrelationID              pgtype.UUID
	CausationID                pgtype.UUID
	CreatedAt                  pgtype.Timestamptz
}

type GlJournalEntryLine struct {
	JournalEntryID       pgtype.UUID
	AccountingScopeID    pgtype.UUID
	LineNumber           int32
	AccountID            pgtype.UUID
	DebitOrCredit        string
	LineCurrencyMode     string
	TransactionAmount    pgtype.Numeric
	FunctionalAmount     pgtype.Numeric
	SegmentCombinationID pgtype.UUID
	LineReference        string
}

type GlLedger struct {
	LedgerID           pgtype.UUID
	AccountingScopeID  pgtype.UUID
	LegalEntityID      pgtype.UUID
	LedgerType         string
	FunctionalCurrency string
	FiscalCalendarID   pgtype.UUID
	LifecycleStatus    string
	EffectiveFrom      pgtype.Date
	EffectiveTo        pgtype.Date
	ApprovalReference  []byte
	AggregateVersion   int64
	RevisionNumber     int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastAuditReference pgtype.UUID
}

type GlLedgerRevision struct {
	LedgerID         pgtype.UUID
	RevisionNumber   int64
	AggregateVersion int64
	Snapshot         []byte
	EffectiveFrom    pgtype.Date
	EffectiveTo      pgtype.Date
	CreatedAt        pgtype.Timestamptz
}

type GlPeriodPostingGate struct {
	AccountingScopeID  pgtype.UUID
	FiscalPeriodID     pgtype.UUID
	GateMode           string
	PeriodStateVersion int64
	GateVersion        int64
	NextLedgerPosition int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type GlPostingAttempt struct {
	PostingAttemptID      pgtype.UUID
	RequestID             pgtype.UUID
	JournalEntryID        pgtype.UUID
	AccountingScopeID     pgtype.UUID
	SourceContext         string
	SourceAggregateType   string
	SourceAggregateID     pgtype.UUID
	SourceVersion         int64
	IdempotencyKey        string
	RequestFingerprint    pgtype.Text
	Outcome               string
	Issues                []byte
	ActorUserID           pgtype.UUID
	ActorSubjectReference string
	CorrelationID         pgtype.UUID
	CausationID           pgtype.UUID
	CreatedAt             pgtype.Timestamptz
}
