#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
generated_dir="${1:-${root}/internal/platform/httpapi/generated}"
expected_file="${root}/scripts/openapi/expected-go-artifacts.txt"
work_dir="$(mktemp -d)"
trap 'rm -rf "${work_dir}"' EXIT

fail() {
  echo "API generation check failed: $1" >&2
  exit 1
}

cd "${root}"
[[ -d "${generated_dir}" ]] || fail "generated output is missing; run make api-generate first"
[[ -f "${expected_file}" ]] || fail "expected artifact inventory is missing"

version="$(go list -m -f '{{.Version}}' github.com/ogen-go/ogen)"
[[ "${version}" == "v1.23.0" ]] || fail "expected ogen v1.23.0, found ${version}"
go mod tidy -diff
bash scripts/openapi/redocly-run.sh lint contracts/openapi/openapi.yaml

first="${work_dir}/first"
second="${work_dir}/second"
bash scripts/openapi/go-generate.sh "${first}" contracts/openapi/openapi.yaml
bash scripts/openapi/go-generate.sh "${second}" contracts/openapi/openapi.yaml

files() {
  find "$1" -type f -printf '%P\n' | LC_ALL=C sort
}

diff -u <(files "${first}") <(files "${second}") || fail "repeated generation is not deterministic"
diff -u "${expected_file}" <(files "${first}") || fail "generated files do not match expected inventory"
diff -ru "${generated_dir}" "${first}" || fail "working-tree generated output is stale"

while IFS= read -r file; do
  [[ -n "${file}" ]] || continue
  [[ -f "${generated_dir}/${file}" ]] || fail "missing generated file: ${file}"
  grep -q '^// Code generated by ogen, DO NOT EDIT\.$' "${generated_dir}/${file}" || fail "missing generated marker: ${file}"
done < <(files "${generated_dir}")

if find "${generated_dir}" -type f -name '*client*' -print -quit | grep -q .; then
  fail "client artifacts must not be generated"
fi

go test ./...
go build ./cmd/api
echo "OpenAPI Go generation verified: ogen ${version}, $(files "${first}" | wc -l | tr -d ' ') artifacts"
