#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
generated_dir="${1:-${root}/web/src/generated/api}"
expected_file="${root}/scripts/openapi/expected-typescript-artifacts.txt"
generated_marker='// This file is auto-generated by @hey-api/openapi-ts'
work_dir="$(mktemp -d "${root}/web/.api-ts-check.XXXXXX")"
trap 'rm -rf "${work_dir}"' EXIT

fail() {
  echo "TypeScript API generation check failed: $1" >&2
  exit 1
}

files() {
  find "$1" -type f -printf '%P\n' | LC_ALL=C sort
}

cd "${root}"
[[ -d "${generated_dir}" ]] || fail "generated output is missing; run make api-ts-generate first"
[[ -s "${expected_file}" ]] || fail "expected artifact inventory is missing or empty"

bash scripts/openapi/redocly-run.sh lint contracts/openapi/openapi.yaml

first="${work_dir}/first"
second="${work_dir}/second"
bundle_directory="$(mktemp -d "${work_dir}/bundle.XXXXXX")"
bundle_file="${bundle_directory}/openapi.bundle.yaml"
bash scripts/openapi/redocly-run.sh bundle contracts/openapi/openapi.yaml --output "${bundle_file}"
bash scripts/openapi/typescript-generate.sh "${first}" "${bundle_file}"
bash scripts/openapi/typescript-generate.sh "${second}" "${bundle_file}"

diff -u <(files "${first}") <(files "${second}") || fail "repeated generation is not deterministic"
diff -u "${expected_file}" <(files "${first}") || fail "generated files do not match expected inventory"

while IFS= read -r file; do
  [[ -n "${file}" ]] || continue
  grep -Fqx "${generated_marker}" <(head -n 1 "${first}/${file}") || fail "missing generated marker in fresh output: ${file}"
done < <(files "${first}")

while IFS= read -r file; do
  [[ -n "${file}" ]] || continue
  [[ -f "${generated_dir}/${file}" ]] || fail "committed generated file is missing: ${file}"
  grep -Fqx "${generated_marker}" <(head -n 1 "${generated_dir}/${file}") || fail "missing generated marker in committed output: ${file}"
done < <(files "${generated_dir}")

[[ -f "${first}/client.gen.ts" ]] || fail "generated Fetch client entrypoint is missing"
if grep -Rqs '@hey-api/client-fetch' "${first}"; then
  fail "generated output must use the bundled Fetch runtime"
fi

fixture_dir="${work_dir}/fixture"
mkdir -p "${fixture_dir}"
cat > "${fixture_dir}/types.ts" <<'EOF'
import type {
  EstablishedResult,
  Money,
  Page,
  ProblemDetails,
} from '../first/types.gen.js'
import { glGetPostingGateStatus } from '../first/sdk.gen.js'

const money: Money = '1250.00'
// @ts-expect-error Money must remain an exact-decimal string.
const invalidMoney: Money = 1250

const established: EstablishedResult = {
  status: 'established',
  aggregateId: '0195a91b-20ab-7c15-8aa8-4e111a8bd620',
  aggregateVersion: 1,
  processId: null,
  correlationId: '0195a91b-20ab-7c15-8aa8-4e111a8bd621',
  links: { self: '/api/v1/status' },
  data: {},
}

const page: Page = { size: 50 }
const problem: ProblemDetails = {
  type: 'about:blank',
  title: 'Validation failed',
  status: 400,
  code: 'VALIDATION_ERROR',
  detail: 'Invalid request',
  correlationId: established.correlationId,
}

void [money, invalidMoney, established, page, problem, glGetPostingGateStatus]
EOF

cat > "${work_dir}/tsconfig.json" <<EOF
{
  "compilerOptions": {
    "target": "es2023",
    "lib": ["ES2023", "DOM"],
    "module": "esnext",
    "moduleResolution": "bundler",
    "noEmit": true,
    "skipLibCheck": true,
    "allowImportingTsExtensions": true,
    "verbatimModuleSyntax": true,
    "strict": true
  },
  "include": ["${first}", "${fixture_dir}"]
}
EOF

pnpm -C "${root}/web" exec tsc --noEmit -p "${work_dir}/tsconfig.json"
echo "TypeScript OpenAPI generation verified: $(files "${first}" | wc -l | tr -d ' ') artifacts"
