#!/usr/bin/env bash
set -Eeuo pipefail
repo_root="$(cd "$(dirname "$BASH_SOURCE")/../.." && pwd)"
environment="${ENVIRONMENT-}"; command_name="$1"; terraform_bin=terraform; az_bin=az; curl_bin=curl; node_bin=node
report_file="$repo_root/artifacts/deployment-smoke/$environment.json"
tmp_dir=; outputs_file=; checks_file=; exit_status=0
fail() { printf 'Azure learning smoke test failed: %s\n' "$*" >&2; exit 1; }
require_command() { command -v "$1" >/dev/null 2>&1 || fail "$1 is required"; }
require_value() { test -n "$(printenv "$1" || true)" || fail "$1 is required"; }
valid_digest() { [[ "$1" =~ ^sha256:[0-9a-f]{64}$ ]]; }
sanitize_detail() { local detail="$1"; detail=${detail//$'\t'/ }; detail=${detail//$'\r'/ }; detail=${detail//$'\n'/ }; printf '%s' "$detail"; }
record_check() { local detail; detail="$(sanitize_detail "$5")"; printf '%s\t%s\t%s\t%s\t%s\n' "$1" "$2" "$3" "$4" "$detail" >> "$checks_file"; printf '[%s] %s (%s/%s): %s\n' "$4" "$1" "$2" "$3" "$detail"; }
run_check() { local id="$1" owner="$2" dependency="$3" fn="$4" detail; shift 4; if detail="$("$fn" "$@" 2>&1)"; then [ -n "$detail" ] || detail=ok; record_check "$id" "$owner" "$dependency" pass "$detail"; else record_check "$id" "$owner" "$dependency" fail "check failed for $id; dependency: $dependency"; exit_status=1; fi; }
output_value() { "$node_bin" -e 'const o=JSON.parse(require("fs").readFileSync(process.argv[1]));const v=o[process.argv[2]]?.value;if(v===undefined||v===null||v==="")process.exit(1);process.stdout.write(String(v))' "$outputs_file" "$1"; }
resource_exists() { local label="$1" id="$2"; "$az_bin" resource show --ids "$id" -o json > "$tmp_dir/$label.json"; "$node_bin" -e 'const x=JSON.parse(require("fs").readFileSync(process.argv[1]));if(!x.id||!["Succeeded","Provisioned"].includes(x.properties?.provisioningState))process.exit(1)' "$tmp_dir/$label.json"; printf '%s exists and is provisioned' "$label"; }
check_outputs() {
	local root="$repo_root/infra/terraform/environments/$environment" key profile
	"$terraform_bin" -chdir="$root" init -reconfigure -input=false -no-color -backend-config="resource_group_name=$TF_STATE_RESOURCE_GROUP" -backend-config="storage_account_name=$TF_STATE_STORAGE_ACCOUNT" -backend-config="container_name=$environment" -backend-config="subscription_id=$ARM_SUBSCRIPTION_ID" -backend-config="tenant_id=$ARM_TENANT_ID" -backend-config=use_azuread_auth=true -lockfile=readonly >/dev/null
	"$terraform_bin" -chdir="$root" output -json -no-color > "$outputs_file"; profile="$(output_value environment_profile)"
	[ "$profile" = "$environment" ] || { echo "environment_profile=$profile does not match ENVIRONMENT=$environment"; return 1; }
	for key in resource_group_id container_app_environment_id api_id static_web_app_id worker_id postgres_server_id database_id key_vault_id log_analytics_workspace_id application_insights_id api_identity_id worker_identity_id container_registry_id api_image_repository api_image_digest worker_image_repository worker_image_digest; do output_value "$key" >/dev/null || { echo "missing Terraform output: $key"; return 1; }; done
	[[ "$(output_value api_image_digest)" =~ ^sha256:[0-9a-f]{64}$ ]] || return 1; [[ "$(output_value worker_image_digest)" =~ ^sha256:[0-9a-f]{64}$ ]] || return 1
	printf 'selected Terraform outputs are present and match %s' "$environment"
}
check_subscription() { [ "$("$az_bin" account show --subscription "$ARM_SUBSCRIPTION_ID" --query id -o tsv)" = "$ARM_SUBSCRIPTION_ID" ] || return 1; printf 'Azure subscription is selected'; }
check_api() {
	local url="$("$node_bin" -e 'const o=JSON.parse(require("fs").readFileSync(process.argv[1]));process.stdout.write(o.api_url.value)' "$outputs_file")" code effective tls
	[[ "$url" =~ ^https://[^/]+$ ]] || { echo "API URL is not HTTPS: $url"; return 1; }
	"$curl_bin" --fail --silent --show-error --location --max-time 15 --retry 3 --write-out '%{http_code} %{url_effective} %{ssl_verify_result}' --output "$tmp_dir/body" "$url/health/live" > "$tmp_dir/meta"; read -r code effective tls < "$tmp_dir/meta"
	[ "$code" = 200 ] && [ "$tls" = 0 ] && [ "$effective" = "$url/health/live" ] || return 1; printf 'HTTPS certificate validated and GET /health/live returned 200'
}
check_json() { local kind="$1" app="$2" digest="$3" identity="$4" file="$tmp_dir/$kind-$app.json"; if [ "$kind" = revision ]; then "$az_bin" containerapp revision list --ids "$(output_value "$app"_id)" -o json > "$file"; else "$az_bin" containerapp show --ids "$(output_value "$app"_id)" -o json > "$file"; fi; "$node_bin" -e 'const x=JSON.parse(require("fs").readFileSync(process.argv[1]));const p=x.properties||{},c=p.template?.containers||[];if(!c.some(x=>String(x.image||"").endsWith("@"+process.argv[2])))process.exit(1);if(process.argv[3]&&!JSON.stringify(p).includes(process.argv[3]))process.exit(1);if(process.argv[4]==="api"&&!c.some(x=>(x.probes||[]).some(q=>q.httpGet?.path==="/health/live")))process.exit(1)' "$file" "$digest" "$identity" "$app"; printf '%s %s uses expected immutable image and identity' "$app" "$kind"; }
check_revision() { local app="$1" digest="$2" file="$tmp_dir/revision-$app.json"; "$az_bin" containerapp revision list --ids "$(output_value "$app"_id)" -o json > "$file"; "$node_bin" -e 'const a=JSON.parse(require("fs").readFileSync(process.argv[1]));if(!Array.isArray(a)||!a.some(x=>["Running","Succeeded","Provisioned"].includes(x.properties?.runningState)||["Succeeded","Provisioned"].includes(x.properties?.provisioningState))||!a.some(x=>(x.properties?.template?.containers||[]).some(c=>String(c.image||"").endsWith("@"+process.argv[2]))))process.exit(1)' "$file" "$digest"; printf '%s has a running/provisioned revision with the expected digest' "$app"; }
check_manifest() { local app="$1" repo="$(output_value "$app"_image_repository)" digest="$(output_value "$app"_image_digest)" result; result="$("$az_bin" acr repository show-manifests --name "$(output_value container_registry_name)" --repository "$repo" --query "[?digest=='$digest'].digest" -o tsv)"; echo "$result" | grep -Fxq "$digest"; printf '%s manifest is present' "$app"; }
check_role() { local identity="$1" scope="$2" role="$3"; "$az_bin" role assignment list --assignee-object-id "$(output_value "$identity"_principal_id)" --scope "$(output_value "$scope")" --all -o json | "$node_bin" -e 'const a=JSON.parse(require("fs").readFileSync(0));if(!a.some(x=>x.roleDefinitionName===process.argv[1]))process.exit(1)' "$role"; printf '%s has scoped %s' "$identity" "$role"; }
check_diagnostics() { "$az_bin" monitor diagnostic-settings list --resource "$(output_value postgres_server_id)" -o json | "$node_bin" -e 'const x=JSON.parse(require("fs").readFileSync(0)),a=x.value||x;if(!Array.isArray(a)||!a.some(d=>{const p=d.properties||d,logs=p.logs||p.enabledLogs||[],metrics=p.metrics||p.enabledMetrics||[];return logs.some(v=>v.category==="PostgreSQLLogs"&&v.enabled!==false)&&metrics.some(v=>v.category==="AllMetrics"&&v.enabled!==false)}))process.exit(1)'; "$az_bin" containerapp env show --ids "$(output_value container_app_environment_id)" --query properties.appLogsConfiguration.destination -o tsv | grep -qx log-analytics; printf 'PostgreSQL logs/metrics and Container Apps Log Analytics are configured'; }
write_report() {
	local completed_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)" outcome=blocked
	[ "$exit_status" -ne 0 ] && outcome=fail; exit_status=1; mkdir -p "$(dirname "$report_file")"
	"$node_bin" - "$checks_file" "$report_file" "$environment" "$(git -C "$repo_root" rev-parse HEAD 2>/dev/null || echo unknown)" "$started_at" "$completed_at" "$outcome" <<'NODE'
const fs=require('fs'),a=process.argv.slice(2),lines=fs.readFileSync(a[0],'utf8').trim().split('\n').filter(Boolean);
const checks=lines.map(x=>{const [id,owner,dependency,status,...d]=x.split('\t');return {id,owner,dependency,status,detail:d.join(' ')}});
const value=k=>{try{return JSON.parse(fs.readFileSync(process.env.SMOKE_OUTPUTS_FILE))[k]?.value??null}catch{return null}};
fs.writeFileSync(a[1],JSON.stringify({story_id:'DLV-IAC-002-us8',commit:a[3],environment:a[2],started_at:a[4],completed_at:a[5],overall_outcome:a[6],cleanup_status:'not-run',migration_status:'not-verified',migration_evidence_reference:null,resource_versions:{api_image:{repository:value('api_image_repository'),digest:value('api_image_digest')},worker_image:{repository:value('worker_image_repository'),digest:value('worker_image_digest')},api_id:value('api_id'),worker_id:value('worker_id'),container_registry_id:value('container_registry_id'),postgres_server_id:value('postgres_server_id')},checks,limitations:['Static Web App content is not deployed by Story 6.','/health/ready is not required; /health/live is the learning-profile probe.','Migrations and release qualification are separately owned.']},null,2)+'\n');
NODE
	printf 'Smoke report: %s\n' "$report_file"
}
self_test() { valid_digest "sha256:$(printf 'a%.0s' {1..64})"; printf 'Azure learning smoke self-tests passed\n'; }
main() {
	[ "$command_name" = --self-test ] && { self_test; return; }; [ "$command_name" = run ] || fail 'Usage: ENVIRONMENT=dev|demo make azure-learning-smoke'; [ "$environment" = dev ] || [ "$environment" = demo ] || fail 'ENVIRONMENT must be dev or demo'
	for name in ARM_SUBSCRIPTION_ID ARM_TENANT_ID TF_STATE_RESOURCE_GROUP TF_STATE_STORAGE_ACCOUNT; do require_value "$name"; done; for bin in "$terraform_bin" "$az_bin" "$curl_bin" "$node_bin"; do require_command "$bin"; done
	tmp_dir="$(mktemp -d)"; outputs_file="$tmp_dir/outputs.json"; checks_file="$tmp_dir/checks.tsv"; : > "$checks_file"; started_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"; trap 'write_report; rm -rf -- "$tmp_dir"; exit "$exit_status"' EXIT; export SMOKE_OUTPUTS_FILE="$outputs_file"
	run_check outputs Terraform state check_outputs; run_check subscription Azure authentication check_subscription
	for pair in resource_group_id:resource-group container_app_environment_id:container-apps-environment api_id:api worker_id:worker static_web_app_id:static-web-app postgres_server_id:postgres key_vault_id:key-vault log_analytics_workspace_id:log-analytics application_insights_id:application-insights api_identity_id:api-identity worker_identity_id:worker-identity container_registry_id:acr; do key="$(echo "$pair"|cut -d: -f1)"; label="$(echo "$pair"|cut -d: -f2)"; run_check "resource-$label" Azure "Terraform output $key" resource_exists "$label" "$(output_value "$key")"; done
	run_check api-health API 'HTTPS and /health/live' check_api; run_check api-config API 'probe and image contract' check_json show api "$(output_value api_image_digest)" "$(output_value api_identity_id)"; run_check worker-config Worker 'image contract' check_json show worker "$(output_value worker_image_digest)" "$(output_value worker_identity_id)"; run_check api-revision API 'revision readiness' check_revision api "$(output_value api_image_digest)"; run_check worker-revision Worker 'revision readiness' check_revision worker "$(output_value worker_image_digest)"
	run_check api-manifest ACR 'immutable API image' check_manifest api; run_check worker-manifest ACR 'immutable worker image' check_manifest worker; run_check api-acr-pull API identity AcrPull check_role api_identity container_registry_id AcrPull; run_check worker-acr-pull Worker identity AcrPull check_role worker_identity container_registry_id AcrPull; run_check api-key-vault API identity 'Key Vault Secrets User' check_role api_identity key_vault_id 'Key Vault Secrets User'; run_check worker-key-vault Worker identity 'Key Vault Secrets User' check_role worker_identity key_vault_id 'Key Vault Secrets User'; run_check diagnostics Platform 'logging and diagnostics' check_diagnostics
	record_check static-web-app-content Platform 'Story 6 frontend deployment' limitation pass 'resource exists; content availability is a known limitation'; record_check migration Release 'separately owned evidence' not-verified 'not executed by this smoke test'
}
main "$@"
