// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: legal_entity.sql

package organizationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLegalEntityRoot = `-- name: GetLegalEntityRoot :one
SELECT id, scope_id, legal_name, functional_currency, presentation_currency,
       tax_registration_id, status, effective_from, effective_to,
       aggregate_version, revision_number, approval_reference,
       created_at, updated_at, last_audit_reference
FROM organization.legal_entity
WHERE id = $1
`

func (q *Queries) GetLegalEntityRoot(ctx context.Context, id pgtype.UUID) (OrganizationLegalEntity, error) {
	row := q.db.QueryRow(ctx, getLegalEntityRoot, id)
	var i OrganizationLegalEntity
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.LegalName,
		&i.FunctionalCurrency,
		&i.PresentationCurrency,
		&i.TaxRegistrationID,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.AggregateVersion,
		&i.RevisionNumber,
		&i.ApprovalReference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAuditReference,
	)
	return i, err
}

const listLegalEntityRoots = `-- name: ListLegalEntityRoots :many
SELECT id, scope_id, legal_name, functional_currency, presentation_currency,
       tax_registration_id, status, effective_from, effective_to,
       aggregate_version, revision_number, approval_reference,
       created_at, updated_at, last_audit_reference
FROM organization.legal_entity
WHERE ($1::uuid IS NULL OR scope_id = $1::uuid)
ORDER BY id
`

func (q *Queries) ListLegalEntityRoots(ctx context.Context, scopeID pgtype.UUID) ([]OrganizationLegalEntity, error) {
	rows, err := q.db.Query(ctx, listLegalEntityRoots, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationLegalEntity
	for rows.Next() {
		var i OrganizationLegalEntity
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.LegalName,
			&i.FunctionalCurrency,
			&i.PresentationCurrency,
			&i.TaxRegistrationID,
			&i.Status,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.AggregateVersion,
			&i.RevisionNumber,
			&i.ApprovalReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAuditReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
