// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package organizationdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrganizationLegalEntity struct {
	ID                   pgtype.UUID
	ScopeID              pgtype.UUID
	LegalName            string
	FunctionalCurrency   string
	PresentationCurrency string
	TaxRegistrationID    pgtype.Text
	Status               string
	EffectiveFrom        pgtype.Date
	EffectiveTo          pgtype.Date
	AggregateVersion     int64
	RevisionNumber       int64
	ApprovalReference    []byte
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	LastAuditReference   pgtype.UUID
}

type OrganizationLegalEntityAddress struct {
	ID            pgtype.UUID
	LegalEntityID pgtype.UUID
	AddressType   string
	Line1         string
	Line2         pgtype.Text
	Locality      string
	Region        pgtype.Text
	PostalCode    string
	CountryCode   string
	EffectiveFrom pgtype.Date
	EffectiveTo   pgtype.Date
}

type OrganizationLegalEntityOwnershipInterest struct {
	ID             pgtype.UUID
	LegalEntityID  pgtype.UUID
	OwnerReference string
	Percentage     pgtype.Numeric
	EffectiveFrom  pgtype.Date
	EffectiveTo    pgtype.Date
}

type OrganizationLegalEntityRegistration struct {
	ID               pgtype.UUID
	LegalEntityID    pgtype.UUID
	RegistrationType string
	Identifier       string
	Jurisdiction     string
	EffectiveFrom    pgtype.Date
	EffectiveTo      pgtype.Date
}

type OrganizationLegalEntityRevision struct {
	LegalEntityID    pgtype.UUID
	RevisionNumber   int64
	AggregateVersion int64
	Snapshot         []byte
	EffectiveFrom    pgtype.Date
	EffectiveTo      pgtype.Date
	CreatedAt        pgtype.Timestamptz
}
