// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package organizationdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrganizationCustomerProfile struct {
	ID                  pgtype.UUID
	ScopeID             pgtype.UUID
	PartyID             pgtype.UUID
	PartyVersion        int64
	CreditTerms         string
	CreditLimitAmount   pgtype.Numeric
	CreditLimitCurrency string
	BillingPreference   string
	TaxTreatment        string
	Status              string
	EffectiveFrom       pgtype.Date
	EffectiveTo         pgtype.Date
	ApprovalReference   []byte
	AggregateVersion    int64
	RevisionNumber      int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	LastAuditReference  pgtype.UUID
}

type OrganizationCustomerProfileRevision struct {
	CustomerProfileID pgtype.UUID
	RevisionNumber    int64
	AggregateVersion  int64
	Snapshot          []byte
	EffectiveFrom     pgtype.Date
	EffectiveTo       pgtype.Date
	CreatedAt         pgtype.Timestamptz
}

type OrganizationFiscalCalendar struct {
	ID                 pgtype.UUID
	ScopeID            pgtype.UUID
	CalendarType       string
	PeriodPattern      string
	Status             string
	EffectiveFrom      pgtype.Date
	EffectiveTo        pgtype.Date
	ApprovalReference  []byte
	AggregateVersion   int64
	RevisionNumber     int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastAuditReference pgtype.UUID
}

type OrganizationFiscalCalendarPeriod struct {
	FiscalCalendarID pgtype.UUID
	PeriodID         pgtype.UUID
	PeriodReference  string
	PeriodOrdinal    int32
	StartDate        pgtype.Date
	EndDate          pgtype.Date
}

type OrganizationFiscalCalendarRevision struct {
	FiscalCalendarID pgtype.UUID
	RevisionNumber   int64
	AggregateVersion int64
	Snapshot         []byte
	EffectiveFrom    pgtype.Date
	EffectiveTo      pgtype.Date
	CreatedAt        pgtype.Timestamptz
}

type OrganizationLegalEntity struct {
	ID                   pgtype.UUID
	ScopeID              pgtype.UUID
	LegalName            string
	FunctionalCurrency   string
	PresentationCurrency string
	TaxRegistrationID    pgtype.Text
	Status               string
	EffectiveFrom        pgtype.Date
	EffectiveTo          pgtype.Date
	AggregateVersion     int64
	RevisionNumber       int64
	ApprovalReference    []byte
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	LastAuditReference   pgtype.UUID
}

type OrganizationLegalEntityAddress struct {
	ID            pgtype.UUID
	LegalEntityID pgtype.UUID
	AddressType   string
	Line1         string
	Line2         pgtype.Text
	Locality      string
	Region        pgtype.Text
	PostalCode    string
	CountryCode   string
	EffectiveFrom pgtype.Date
	EffectiveTo   pgtype.Date
}

type OrganizationLegalEntityOwnershipInterest struct {
	ID             pgtype.UUID
	LegalEntityID  pgtype.UUID
	OwnerReference string
	Percentage     pgtype.Numeric
	EffectiveFrom  pgtype.Date
	EffectiveTo    pgtype.Date
}

type OrganizationLegalEntityRegistration struct {
	ID               pgtype.UUID
	LegalEntityID    pgtype.UUID
	RegistrationType string
	Identifier       string
	Jurisdiction     string
	EffectiveFrom    pgtype.Date
	EffectiveTo      pgtype.Date
}

type OrganizationLegalEntityRevision struct {
	LegalEntityID    pgtype.UUID
	RevisionNumber   int64
	AggregateVersion int64
	Snapshot         []byte
	EffectiveFrom    pgtype.Date
	EffectiveTo      pgtype.Date
	CreatedAt        pgtype.Timestamptz
}

type OrganizationMasterDataPublication struct {
	PublicationID         pgtype.UUID
	AggregateType         string
	AggregateID           pgtype.UUID
	ScopeID               pgtype.UUID
	AggregateVersion      int64
	RevisionNumber        int64
	Status                string
	DependentAvailability string
	EventType             string
	EventVersion          int32
	MessageID             pgtype.UUID
	EffectiveFrom         pgtype.Date
	EffectiveTo           pgtype.Date
	ApprovalReference     []byte
	SourceFingerprint     string
	AuditReference        pgtype.UUID
	PublishedAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type OrganizationParty struct {
	ID                 pgtype.UUID
	ScopeID            pgtype.UUID
	Name               string
	PartyType          string
	Status             string
	TaxIdentifier      pgtype.Text
	BankControl        []byte
	AggregateVersion   int64
	RevisionNumber     int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastAuditReference pgtype.UUID
}

type OrganizationPartyAddress struct {
	ID          pgtype.UUID
	PartyID     pgtype.UUID
	AddressType string
	Line1       string
	Line2       pgtype.Text
	Locality    string
	Region      pgtype.Text
	PostalCode  string
	CountryCode string
}

type OrganizationPartyBankDetailReference struct {
	ID               pgtype.UUID
	PartyID          pgtype.UUID
	Reference        string
	ProviderCode     pgtype.Text
	ConsentReference pgtype.Text
}

type OrganizationPartyClassification struct {
	ID                  pgtype.UUID
	PartyID             pgtype.UUID
	ClassificationCode  string
	ClassificationValue string
}

type OrganizationPartyContactMethod struct {
	ID           pgtype.UUID
	PartyID      pgtype.UUID
	ContactType  string
	ContactValue string
	Label        pgtype.Text
}

type OrganizationPartyRevision struct {
	PartyID          pgtype.UUID
	RevisionNumber   int64
	AggregateVersion int64
	Snapshot         []byte
	CreatedAt        pgtype.Timestamptz
}

type OrganizationVendorProfile struct {
	ID                   pgtype.UUID
	ScopeID              pgtype.UUID
	PartyID              pgtype.UUID
	PartyVersion         int64
	PaymentTerms         string
	WithholdingTreatment string
	RemittancePreference string
	Status               string
	EffectiveFrom        pgtype.Date
	EffectiveTo          pgtype.Date
	ApprovalReference    []byte
	AggregateVersion     int64
	RevisionNumber       int64
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	LastAuditReference   pgtype.UUID
}

type OrganizationVendorProfileRevision struct {
	VendorProfileID  pgtype.UUID
	RevisionNumber   int64
	AggregateVersion int64
	Snapshot         []byte
	EffectiveFrom    pgtype.Date
	EffectiveTo      pgtype.Date
	CreatedAt        pgtype.Timestamptz
}
