// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: party.sql

package organizationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPartyRoot = `-- name: GetPartyRoot :one
SELECT id, scope_id, name, party_type, status, tax_identifier, bank_control,
       aggregate_version, revision_number, created_at, updated_at, last_audit_reference
FROM organization.party
WHERE id = $1
`

func (q *Queries) GetPartyRoot(ctx context.Context, id pgtype.UUID) (OrganizationParty, error) {
	row := q.db.QueryRow(ctx, getPartyRoot, id)
	var i OrganizationParty
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.Name,
		&i.PartyType,
		&i.Status,
		&i.TaxIdentifier,
		&i.BankControl,
		&i.AggregateVersion,
		&i.RevisionNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAuditReference,
	)
	return i, err
}

const listPartyRoots = `-- name: ListPartyRoots :many
SELECT id, scope_id, name, party_type, status, tax_identifier, bank_control,
       aggregate_version, revision_number, created_at, updated_at, last_audit_reference
FROM organization.party
WHERE ($1::uuid IS NULL OR scope_id = $1::uuid)
ORDER BY id
`

func (q *Queries) ListPartyRoots(ctx context.Context, scopeID pgtype.UUID) ([]OrganizationParty, error) {
	rows, err := q.db.Query(ctx, listPartyRoots, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationParty
	for rows.Next() {
		var i OrganizationParty
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.Name,
			&i.PartyType,
			&i.Status,
			&i.TaxIdentifier,
			&i.BankControl,
			&i.AggregateVersion,
			&i.RevisionNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAuditReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
