// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_policy.sql

package identitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentIdentityAccessPolicyVersion = `-- name: GetCurrentIdentityAccessPolicyVersion :one
SELECT current_version
FROM identity.access_policy
WHERE id = $1
`

func (q *Queries) GetCurrentIdentityAccessPolicyVersion(ctx context.Context, policyID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getCurrentIdentityAccessPolicyVersion, policyID)
	var current_version string
	err := row.Scan(&current_version)
	return current_version, err
}

const listCurrentIdentityAccessPolicies = `-- name: ListCurrentIdentityAccessPolicies :many
SELECT
    r.policy_id,
    r.policy_version,
    p.status,
    r.effective_from,
    r.effective_to,
    to_jsonb(r.subject_actor_ids) AS subject_actor_ids,
    to_jsonb(r.subject_role_ids) AS subject_role_ids,
    to_jsonb(r.permissions) AS permissions,
    r.rules
FROM identity.access_policy_revision AS r
JOIN identity.access_policy AS p
  ON p.id = r.policy_id
 AND p.current_version = r.policy_version
ORDER BY r.policy_id
`

type ListCurrentIdentityAccessPoliciesRow struct {
	PolicyID        pgtype.UUID
	PolicyVersion   string
	Status          string
	EffectiveFrom   pgtype.Timestamptz
	EffectiveTo     pgtype.Timestamptz
	SubjectActorIds []byte
	SubjectRoleIds  []byte
	Permissions     []byte
	Rules           []byte
}

func (q *Queries) ListCurrentIdentityAccessPolicies(ctx context.Context) ([]ListCurrentIdentityAccessPoliciesRow, error) {
	rows, err := q.db.Query(ctx, listCurrentIdentityAccessPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentIdentityAccessPoliciesRow
	for rows.Next() {
		var i ListCurrentIdentityAccessPoliciesRow
		if err := rows.Scan(
			&i.PolicyID,
			&i.PolicyVersion,
			&i.Status,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.SubjectActorIds,
			&i.SubjectRoleIds,
			&i.Permissions,
			&i.Rules,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
