// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: emergency_access_grant.sql

package identitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentityEmergencyAccessGrant = `-- name: CreateIdentityEmergencyAccessGrant :exec
INSERT INTO identity.emergency_access_grant (
    id, target_actor_id, current_version, status, created_at, updated_at, last_audit_reference
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
`

type CreateIdentityEmergencyAccessGrantParams struct {
	ID                 pgtype.UUID
	TargetActorID      pgtype.UUID
	CurrentVersion     int64
	Status             string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastAuditReference pgtype.UUID
}

func (q *Queries) CreateIdentityEmergencyAccessGrant(ctx context.Context, arg CreateIdentityEmergencyAccessGrantParams) error {
	_, err := q.db.Exec(ctx, createIdentityEmergencyAccessGrant,
		arg.ID,
		arg.TargetActorID,
		arg.CurrentVersion,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastAuditReference,
	)
	return err
}

const createIdentityEmergencyAccessGrantPermission = `-- name: CreateIdentityEmergencyAccessGrantPermission :exec
INSERT INTO identity.emergency_access_grant_permission (grant_id, grant_version, permission)
VALUES ($1, $2, $3)
`

type CreateIdentityEmergencyAccessGrantPermissionParams struct {
	GrantID      pgtype.UUID
	GrantVersion int64
	Permission   string
}

func (q *Queries) CreateIdentityEmergencyAccessGrantPermission(ctx context.Context, arg CreateIdentityEmergencyAccessGrantPermissionParams) error {
	_, err := q.db.Exec(ctx, createIdentityEmergencyAccessGrantPermission, arg.GrantID, arg.GrantVersion, arg.Permission)
	return err
}

const createIdentityEmergencyAccessGrantRevision = `-- name: CreateIdentityEmergencyAccessGrantRevision :exec
INSERT INTO identity.emergency_access_grant_revision (
    grant_id, revision_version, target_actor_id, status, reason_code, granting_actor_id,
    approver_user_id, approval_request_id, approval_decision_id, policy_version,
    decision_version, subject_version, candidate_fingerprint, start_at, expires_at,
    review_status, review_outcome_code, review_reference, review_due_at, revoked_at,
    revoked_by, revocation_reason, audit_reference, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16, $17,
    $18, $19, $20, $21,
    $22, $23, $24
)
`

type CreateIdentityEmergencyAccessGrantRevisionParams struct {
	GrantID              pgtype.UUID
	RevisionVersion      int64
	TargetActorID        pgtype.UUID
	Status               string
	ReasonCode           string
	GrantingActorID      pgtype.UUID
	ApproverUserID       pgtype.UUID
	ApprovalRequestID    pgtype.UUID
	ApprovalDecisionID   pgtype.UUID
	PolicyVersion        string
	DecisionVersion      int64
	SubjectVersion       int64
	CandidateFingerprint string
	StartAt              pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
	ReviewStatus         string
	ReviewOutcomeCode    pgtype.Text
	ReviewReference      pgtype.Text
	ReviewDueAt          pgtype.Timestamptz
	RevokedAt            pgtype.Timestamptz
	RevokedBy            pgtype.UUID
	RevocationReason     pgtype.Text
	AuditReference       pgtype.UUID
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) CreateIdentityEmergencyAccessGrantRevision(ctx context.Context, arg CreateIdentityEmergencyAccessGrantRevisionParams) error {
	_, err := q.db.Exec(ctx, createIdentityEmergencyAccessGrantRevision,
		arg.GrantID,
		arg.RevisionVersion,
		arg.TargetActorID,
		arg.Status,
		arg.ReasonCode,
		arg.GrantingActorID,
		arg.ApproverUserID,
		arg.ApprovalRequestID,
		arg.ApprovalDecisionID,
		arg.PolicyVersion,
		arg.DecisionVersion,
		arg.SubjectVersion,
		arg.CandidateFingerprint,
		arg.StartAt,
		arg.ExpiresAt,
		arg.ReviewStatus,
		arg.ReviewOutcomeCode,
		arg.ReviewReference,
		arg.ReviewDueAt,
		arg.RevokedAt,
		arg.RevokedBy,
		arg.RevocationReason,
		arg.AuditReference,
		arg.CreatedAt,
	)
	return err
}

const createIdentityEmergencyAccessGrantScope = `-- name: CreateIdentityEmergencyAccessGrantScope :exec
INSERT INTO identity.emergency_access_grant_scope (grant_id, grant_version, scope_id)
VALUES ($1, $2, $3)
`

type CreateIdentityEmergencyAccessGrantScopeParams struct {
	GrantID      pgtype.UUID
	GrantVersion int64
	ScopeID      string
}

func (q *Queries) CreateIdentityEmergencyAccessGrantScope(ctx context.Context, arg CreateIdentityEmergencyAccessGrantScopeParams) error {
	_, err := q.db.Exec(ctx, createIdentityEmergencyAccessGrantScope, arg.GrantID, arg.GrantVersion, arg.ScopeID)
	return err
}

const getIdentityEmergencyAccessGrant = `-- name: GetIdentityEmergencyAccessGrant :one
SELECT
    g.id,
    g.target_actor_id,
    g.current_version,
    g.status,
    g.created_at,
    g.updated_at,
    g.last_audit_reference,
    r.reason_code,
    r.granting_actor_id,
    r.approver_user_id,
    r.approval_request_id,
    r.approval_decision_id,
    r.policy_version,
    r.decision_version,
    r.subject_version,
    r.candidate_fingerprint,
    r.start_at,
    r.expires_at,
    r.review_status,
    r.review_outcome_code,
    r.review_reference,
    r.review_due_at,
    r.revoked_at,
    r.revoked_by,
    r.revocation_reason,
    r.audit_reference,
    r.created_at AS revision_created_at
FROM identity.emergency_access_grant AS g
JOIN identity.emergency_access_grant_revision AS r
  ON r.grant_id = g.id
 AND r.revision_version = g.current_version
WHERE g.id = $1
`

type GetIdentityEmergencyAccessGrantRow struct {
	ID                   pgtype.UUID
	TargetActorID        pgtype.UUID
	CurrentVersion       int64
	Status               string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	LastAuditReference   pgtype.UUID
	ReasonCode           string
	GrantingActorID      pgtype.UUID
	ApproverUserID       pgtype.UUID
	ApprovalRequestID    pgtype.UUID
	ApprovalDecisionID   pgtype.UUID
	PolicyVersion        string
	DecisionVersion      int64
	SubjectVersion       int64
	CandidateFingerprint string
	StartAt              pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
	ReviewStatus         string
	ReviewOutcomeCode    pgtype.Text
	ReviewReference      pgtype.Text
	ReviewDueAt          pgtype.Timestamptz
	RevokedAt            pgtype.Timestamptz
	RevokedBy            pgtype.UUID
	RevocationReason     pgtype.Text
	AuditReference       pgtype.UUID
	RevisionCreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetIdentityEmergencyAccessGrant(ctx context.Context, id pgtype.UUID) (GetIdentityEmergencyAccessGrantRow, error) {
	row := q.db.QueryRow(ctx, getIdentityEmergencyAccessGrant, id)
	var i GetIdentityEmergencyAccessGrantRow
	err := row.Scan(
		&i.ID,
		&i.TargetActorID,
		&i.CurrentVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAuditReference,
		&i.ReasonCode,
		&i.GrantingActorID,
		&i.ApproverUserID,
		&i.ApprovalRequestID,
		&i.ApprovalDecisionID,
		&i.PolicyVersion,
		&i.DecisionVersion,
		&i.SubjectVersion,
		&i.CandidateFingerprint,
		&i.StartAt,
		&i.ExpiresAt,
		&i.ReviewStatus,
		&i.ReviewOutcomeCode,
		&i.ReviewReference,
		&i.ReviewDueAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevocationReason,
		&i.AuditReference,
		&i.RevisionCreatedAt,
	)
	return i, err
}

const listIdentityEmergencyAccessGrantPermissions = `-- name: ListIdentityEmergencyAccessGrantPermissions :many
SELECT permission
FROM identity.emergency_access_grant_permission
WHERE grant_id = $1
  AND grant_version = $2
ORDER BY permission
`

type ListIdentityEmergencyAccessGrantPermissionsParams struct {
	GrantID      pgtype.UUID
	GrantVersion int64
}

func (q *Queries) ListIdentityEmergencyAccessGrantPermissions(ctx context.Context, arg ListIdentityEmergencyAccessGrantPermissionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listIdentityEmergencyAccessGrantPermissions, arg.GrantID, arg.GrantVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentityEmergencyAccessGrantScopes = `-- name: ListIdentityEmergencyAccessGrantScopes :many
SELECT scope_id
FROM identity.emergency_access_grant_scope
WHERE grant_id = $1
  AND grant_version = $2
ORDER BY scope_id
`

type ListIdentityEmergencyAccessGrantScopesParams struct {
	GrantID      pgtype.UUID
	GrantVersion int64
}

func (q *Queries) ListIdentityEmergencyAccessGrantScopes(ctx context.Context, arg ListIdentityEmergencyAccessGrantScopesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listIdentityEmergencyAccessGrantScopes, arg.GrantID, arg.GrantVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var scope_id string
		if err := rows.Scan(&scope_id); err != nil {
			return nil, err
		}
		items = append(items, scope_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentityEmergencyAccessGrants = `-- name: ListIdentityEmergencyAccessGrants :many
SELECT
    g.id,
    g.target_actor_id,
    g.current_version,
    g.status,
    g.created_at,
    g.updated_at,
    g.last_audit_reference,
    r.reason_code,
    r.granting_actor_id,
    r.approver_user_id,
    r.approval_request_id,
    r.approval_decision_id,
    r.policy_version,
    r.decision_version,
    r.subject_version,
    r.candidate_fingerprint,
    r.start_at,
    r.expires_at,
    r.review_status,
    r.review_outcome_code,
    r.review_reference,
    r.review_due_at,
    r.revoked_at,
    r.revoked_by,
    r.revocation_reason,
    r.audit_reference,
    r.created_at AS revision_created_at
FROM identity.emergency_access_grant AS g
JOIN identity.emergency_access_grant_revision AS r
  ON r.grant_id = g.id
 AND r.revision_version = g.current_version
ORDER BY g.id
`

type ListIdentityEmergencyAccessGrantsRow struct {
	ID                   pgtype.UUID
	TargetActorID        pgtype.UUID
	CurrentVersion       int64
	Status               string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	LastAuditReference   pgtype.UUID
	ReasonCode           string
	GrantingActorID      pgtype.UUID
	ApproverUserID       pgtype.UUID
	ApprovalRequestID    pgtype.UUID
	ApprovalDecisionID   pgtype.UUID
	PolicyVersion        string
	DecisionVersion      int64
	SubjectVersion       int64
	CandidateFingerprint string
	StartAt              pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
	ReviewStatus         string
	ReviewOutcomeCode    pgtype.Text
	ReviewReference      pgtype.Text
	ReviewDueAt          pgtype.Timestamptz
	RevokedAt            pgtype.Timestamptz
	RevokedBy            pgtype.UUID
	RevocationReason     pgtype.Text
	AuditReference       pgtype.UUID
	RevisionCreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListIdentityEmergencyAccessGrants(ctx context.Context) ([]ListIdentityEmergencyAccessGrantsRow, error) {
	rows, err := q.db.Query(ctx, listIdentityEmergencyAccessGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentityEmergencyAccessGrantsRow
	for rows.Next() {
		var i ListIdentityEmergencyAccessGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetActorID,
			&i.CurrentVersion,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAuditReference,
			&i.ReasonCode,
			&i.GrantingActorID,
			&i.ApproverUserID,
			&i.ApprovalRequestID,
			&i.ApprovalDecisionID,
			&i.PolicyVersion,
			&i.DecisionVersion,
			&i.SubjectVersion,
			&i.CandidateFingerprint,
			&i.StartAt,
			&i.ExpiresAt,
			&i.ReviewStatus,
			&i.ReviewOutcomeCode,
			&i.ReviewReference,
			&i.ReviewDueAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevocationReason,
			&i.AuditReference,
			&i.RevisionCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIdentityEmergencyAccessGrantAuditReference = `-- name: SetIdentityEmergencyAccessGrantAuditReference :exec
UPDATE identity.emergency_access_grant
SET last_audit_reference = $1
WHERE id = $2
`

type SetIdentityEmergencyAccessGrantAuditReferenceParams struct {
	LastAuditReference pgtype.UUID
	ID                 pgtype.UUID
}

func (q *Queries) SetIdentityEmergencyAccessGrantAuditReference(ctx context.Context, arg SetIdentityEmergencyAccessGrantAuditReferenceParams) error {
	_, err := q.db.Exec(ctx, setIdentityEmergencyAccessGrantAuditReference, arg.LastAuditReference, arg.ID)
	return err
}

const updateIdentityEmergencyAccessGrant = `-- name: UpdateIdentityEmergencyAccessGrant :execrows
UPDATE identity.emergency_access_grant
SET current_version = $1,
    status = $2,
    updated_at = $3,
    last_audit_reference = $4
WHERE id = $5
  AND current_version = $6
`

type UpdateIdentityEmergencyAccessGrantParams struct {
	NextCurrentVersion     int64
	Status                 string
	UpdatedAt              pgtype.Timestamptz
	LastAuditReference     pgtype.UUID
	ID                     pgtype.UUID
	ExpectedCurrentVersion int64
}

func (q *Queries) UpdateIdentityEmergencyAccessGrant(ctx context.Context, arg UpdateIdentityEmergencyAccessGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIdentityEmergencyAccessGrant,
		arg.NextCurrentVersion,
		arg.Status,
		arg.UpdatedAt,
		arg.LastAuditReference,
		arg.ID,
		arg.ExpectedCurrentVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
