// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdentityUserAccount struct {
	ID                       pgtype.UUID
	AuthenticationSubjectOid string
	AuthenticationSubjectTid string
	AuthenticationSubjectSub string
	Status                   string
	AggregateVersion         int64
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	LastAuditReference       pgtype.UUID
}

type IdentityUserRoleAssignment struct {
	UserID pgtype.UUID
	RoleID pgtype.UUID
}

type IdentityUserRoleAssignmentScope struct {
	UserID  pgtype.UUID
	RoleID  pgtype.UUID
	ScopeID string
}
