// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdentityAccessPolicy struct {
	ID             pgtype.UUID
	CurrentVersion string
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type IdentityAccessPolicyRevision struct {
	PolicyID        pgtype.UUID
	PolicyVersion   string
	Status          string
	EffectiveFrom   pgtype.Timestamptz
	EffectiveTo     pgtype.Timestamptz
	SubjectActorIds []pgtype.UUID
	SubjectRoleIds  []pgtype.UUID
	Permissions     []string
	Rules           []byte
	CreatedAt       pgtype.Timestamptz
}

type IdentityRole struct {
	ID                 pgtype.UUID
	Name               string
	Status             string
	AggregateVersion   int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastAuditReference pgtype.UUID
}

type IdentityRolePermissionGrant struct {
	RoleID        pgtype.UUID
	RoleVersion   int64
	Permission    string
	ScopeID       string
	EffectiveFrom pgtype.Timestamptz
	EffectiveTo   pgtype.Timestamptz
}

type IdentityRoleRevision struct {
	RoleID               pgtype.UUID
	RevisionVersion      int64
	Name                 string
	Status               string
	ApprovalRequestID    pgtype.UUID
	ApprovalDecisionID   pgtype.UUID
	ApproverUserID       pgtype.UUID
	PolicyVersion        string
	DecisionVersion      int64
	SubjectVersion       int64
	CandidateFingerprint string
	AuditReference       pgtype.UUID
	CreatedAt            pgtype.Timestamptz
}

type IdentityUserAccount struct {
	ID                       pgtype.UUID
	AuthenticationSubjectOid string
	AuthenticationSubjectTid string
	AuthenticationSubjectSub string
	Status                   string
	AggregateVersion         int64
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	LastAuditReference       pgtype.UUID
}

type IdentityUserRoleAssignment struct {
	UserID pgtype.UUID
	RoleID pgtype.UUID
}

type IdentityUserRoleAssignmentScope struct {
	UserID  pgtype.UUID
	RoleID  pgtype.UUID
	ScopeID string
}
