// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdentityAccessPolicy struct {
	ID             pgtype.UUID
	CurrentVersion string
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type IdentityAccessPolicyRevision struct {
	PolicyID        pgtype.UUID
	PolicyVersion   string
	Status          string
	EffectiveFrom   pgtype.Timestamptz
	EffectiveTo     pgtype.Timestamptz
	SubjectActorIds []pgtype.UUID
	SubjectRoleIds  []pgtype.UUID
	Permissions     []string
	Rules           []byte
	CreatedAt       pgtype.Timestamptz
}

type IdentityEmergencyAccessGrant struct {
	ID                 pgtype.UUID
	TargetActorID      pgtype.UUID
	CurrentVersion     int64
	Status             string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastAuditReference pgtype.UUID
}

type IdentityEmergencyAccessGrantPermission struct {
	GrantID      pgtype.UUID
	GrantVersion int64
	Permission   string
}

type IdentityEmergencyAccessGrantRevision struct {
	GrantID              pgtype.UUID
	RevisionVersion      int64
	TargetActorID        pgtype.UUID
	Status               string
	ReasonCode           string
	GrantingActorID      pgtype.UUID
	ApproverUserID       pgtype.UUID
	ApprovalRequestID    pgtype.UUID
	ApprovalDecisionID   pgtype.UUID
	PolicyVersion        string
	DecisionVersion      int64
	SubjectVersion       int64
	CandidateFingerprint string
	StartAt              pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
	ReviewStatus         string
	ReviewOutcomeCode    pgtype.Text
	ReviewReference      pgtype.Text
	ReviewDueAt          pgtype.Timestamptz
	RevokedAt            pgtype.Timestamptz
	RevokedBy            pgtype.UUID
	RevocationReason     pgtype.Text
	AuditReference       pgtype.UUID
	CreatedAt            pgtype.Timestamptz
}

type IdentityEmergencyAccessGrantScope struct {
	GrantID      pgtype.UUID
	GrantVersion int64
	ScopeID      string
}

type IdentityRole struct {
	ID                 pgtype.UUID
	Name               string
	Status             string
	AggregateVersion   int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastAuditReference pgtype.UUID
}

type IdentityRolePermissionGrant struct {
	RoleID        pgtype.UUID
	RoleVersion   int64
	Permission    string
	ScopeID       string
	EffectiveFrom pgtype.Timestamptz
	EffectiveTo   pgtype.Timestamptz
}

type IdentityRoleRevision struct {
	RoleID               pgtype.UUID
	RevisionVersion      int64
	Name                 string
	Status               string
	ApprovalRequestID    pgtype.UUID
	ApprovalDecisionID   pgtype.UUID
	ApproverUserID       pgtype.UUID
	PolicyVersion        string
	DecisionVersion      int64
	SubjectVersion       int64
	CandidateFingerprint string
	AuditReference       pgtype.UUID
	CreatedAt            pgtype.Timestamptz
}

type IdentitySegregationRule struct {
	ID                 pgtype.UUID
	Code               string
	CurrentVersion     int64
	Status             string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastAuditReference pgtype.UUID
}

type IdentitySegregationRuleRevision struct {
	RuleID                 pgtype.UUID
	RevisionVersion        int64
	Code                   string
	Name                   string
	Status                 string
	ConflictingPermissions []string
	EnforcementMode        string
	ScopeIds               []string
	AmountThreshold        pgtype.Numeric
	CoolingOffSeconds      int64
	EffectiveFrom          pgtype.Timestamptz
	EffectiveTo            pgtype.Timestamptz
	ApprovalRequestID      pgtype.UUID
	ApprovalDecisionID     pgtype.UUID
	ApproverUserID         pgtype.UUID
	PolicyVersion          string
	DecisionVersion        int64
	SubjectVersion         int64
	CandidateFingerprint   string
	AuditReference         pgtype.UUID
	CreatedAt              pgtype.Timestamptz
}

type IdentityUserAccount struct {
	ID                       pgtype.UUID
	AuthenticationSubjectOid string
	AuthenticationSubjectTid string
	AuthenticationSubjectSub string
	Status                   string
	AggregateVersion         int64
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	LastAuditReference       pgtype.UUID
}

type IdentityUserRoleAssignment struct {
	UserID pgtype.UUID
	RoleID pgtype.UUID
}

type IdentityUserRoleAssignmentScope struct {
	UserID  pgtype.UUID
	RoleID  pgtype.UUID
	ScopeID string
}
