// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role.sql

package identitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentityRole = `-- name: CreateIdentityRole :exec
INSERT INTO identity.role (
    id,
    name,
    status,
    aggregate_version,
    created_at,
    updated_at,
    last_audit_reference
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type CreateIdentityRoleParams struct {
	ID                 pgtype.UUID
	Name               string
	Status             string
	AggregateVersion   int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastAuditReference pgtype.UUID
}

func (q *Queries) CreateIdentityRole(ctx context.Context, arg CreateIdentityRoleParams) error {
	_, err := q.db.Exec(ctx, createIdentityRole,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.AggregateVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastAuditReference,
	)
	return err
}

const createIdentityRoleGrant = `-- name: CreateIdentityRoleGrant :exec
INSERT INTO identity.role_permission_grant (
    role_id,
    role_version,
    permission,
    scope_id,
    effective_from,
    effective_to
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type CreateIdentityRoleGrantParams struct {
	RoleID        pgtype.UUID
	RoleVersion   int64
	Permission    string
	ScopeID       string
	EffectiveFrom pgtype.Timestamptz
	EffectiveTo   pgtype.Timestamptz
}

func (q *Queries) CreateIdentityRoleGrant(ctx context.Context, arg CreateIdentityRoleGrantParams) error {
	_, err := q.db.Exec(ctx, createIdentityRoleGrant,
		arg.RoleID,
		arg.RoleVersion,
		arg.Permission,
		arg.ScopeID,
		arg.EffectiveFrom,
		arg.EffectiveTo,
	)
	return err
}

const createIdentityRoleRevision = `-- name: CreateIdentityRoleRevision :exec
INSERT INTO identity.role_revision (
    role_id,
    revision_version,
    name,
    status,
    approval_request_id,
    approval_decision_id,
    approver_user_id,
    policy_version,
    decision_version,
    subject_version,
    candidate_fingerprint,
    audit_reference,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
`

type CreateIdentityRoleRevisionParams struct {
	RoleID               pgtype.UUID
	RevisionVersion      int64
	Name                 string
	Status               string
	ApprovalRequestID    pgtype.UUID
	ApprovalDecisionID   pgtype.UUID
	ApproverUserID       pgtype.UUID
	PolicyVersion        string
	DecisionVersion      int64
	SubjectVersion       int64
	CandidateFingerprint string
	AuditReference       pgtype.UUID
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) CreateIdentityRoleRevision(ctx context.Context, arg CreateIdentityRoleRevisionParams) error {
	_, err := q.db.Exec(ctx, createIdentityRoleRevision,
		arg.RoleID,
		arg.RevisionVersion,
		arg.Name,
		arg.Status,
		arg.ApprovalRequestID,
		arg.ApprovalDecisionID,
		arg.ApproverUserID,
		arg.PolicyVersion,
		arg.DecisionVersion,
		arg.SubjectVersion,
		arg.CandidateFingerprint,
		arg.AuditReference,
		arg.CreatedAt,
	)
	return err
}

const getIdentityRole = `-- name: GetIdentityRole :one
SELECT
    r.id,
    r.name,
    r.status,
    r.aggregate_version,
    r.created_at,
    r.updated_at,
    r.last_audit_reference,
    rr.approval_request_id,
    rr.approval_decision_id,
    rr.approver_user_id,
    rr.policy_version,
    rr.decision_version,
    rr.subject_version,
    rr.candidate_fingerprint,
    rr.audit_reference,
    rr.created_at AS revision_created_at
FROM identity.role AS r
JOIN identity.role_revision AS rr
  ON rr.role_id = r.id
 AND rr.revision_version = r.aggregate_version
WHERE r.id = $1
`

type GetIdentityRoleRow struct {
	ID                   pgtype.UUID
	Name                 string
	Status               string
	AggregateVersion     int64
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	LastAuditReference   pgtype.UUID
	ApprovalRequestID    pgtype.UUID
	ApprovalDecisionID   pgtype.UUID
	ApproverUserID       pgtype.UUID
	PolicyVersion        string
	DecisionVersion      int64
	SubjectVersion       int64
	CandidateFingerprint string
	AuditReference       pgtype.UUID
	RevisionCreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetIdentityRole(ctx context.Context, id pgtype.UUID) (GetIdentityRoleRow, error) {
	row := q.db.QueryRow(ctx, getIdentityRole, id)
	var i GetIdentityRoleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.AggregateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAuditReference,
		&i.ApprovalRequestID,
		&i.ApprovalDecisionID,
		&i.ApproverUserID,
		&i.PolicyVersion,
		&i.DecisionVersion,
		&i.SubjectVersion,
		&i.CandidateFingerprint,
		&i.AuditReference,
		&i.RevisionCreatedAt,
	)
	return i, err
}

const listIdentityRoleGrants = `-- name: ListIdentityRoleGrants :many
SELECT
    role_id,
    role_version,
    permission,
    scope_id,
    effective_from,
    effective_to
FROM identity.role_permission_grant
WHERE role_id = $1
  AND role_version = $2
ORDER BY permission, scope_id, effective_from
`

type ListIdentityRoleGrantsParams struct {
	RoleID      pgtype.UUID
	RoleVersion int64
}

func (q *Queries) ListIdentityRoleGrants(ctx context.Context, arg ListIdentityRoleGrantsParams) ([]IdentityRolePermissionGrant, error) {
	rows, err := q.db.Query(ctx, listIdentityRoleGrants, arg.RoleID, arg.RoleVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityRolePermissionGrant
	for rows.Next() {
		var i IdentityRolePermissionGrant
		if err := rows.Scan(
			&i.RoleID,
			&i.RoleVersion,
			&i.Permission,
			&i.ScopeID,
			&i.EffectiveFrom,
			&i.EffectiveTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentityRoles = `-- name: ListIdentityRoles :many
SELECT
    r.id,
    r.name,
    r.status,
    r.aggregate_version,
    r.created_at,
    r.updated_at,
    r.last_audit_reference,
    rr.approval_request_id,
    rr.approval_decision_id,
    rr.approver_user_id,
    rr.policy_version,
    rr.decision_version,
    rr.subject_version,
    rr.candidate_fingerprint,
    rr.audit_reference,
    rr.created_at AS revision_created_at
FROM identity.role AS r
JOIN identity.role_revision AS rr
  ON rr.role_id = r.id
 AND rr.revision_version = r.aggregate_version
ORDER BY r.id
`

type ListIdentityRolesRow struct {
	ID                   pgtype.UUID
	Name                 string
	Status               string
	AggregateVersion     int64
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	LastAuditReference   pgtype.UUID
	ApprovalRequestID    pgtype.UUID
	ApprovalDecisionID   pgtype.UUID
	ApproverUserID       pgtype.UUID
	PolicyVersion        string
	DecisionVersion      int64
	SubjectVersion       int64
	CandidateFingerprint string
	AuditReference       pgtype.UUID
	RevisionCreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListIdentityRoles(ctx context.Context) ([]ListIdentityRolesRow, error) {
	rows, err := q.db.Query(ctx, listIdentityRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentityRolesRow
	for rows.Next() {
		var i ListIdentityRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.AggregateVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAuditReference,
			&i.ApprovalRequestID,
			&i.ApprovalDecisionID,
			&i.ApproverUserID,
			&i.PolicyVersion,
			&i.DecisionVersion,
			&i.SubjectVersion,
			&i.CandidateFingerprint,
			&i.AuditReference,
			&i.RevisionCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIdentityRoleAuditReference = `-- name: SetIdentityRoleAuditReference :exec
UPDATE identity.role
SET last_audit_reference = $1
WHERE id = $2
`

type SetIdentityRoleAuditReferenceParams struct {
	LastAuditReference pgtype.UUID
	ID                 pgtype.UUID
}

func (q *Queries) SetIdentityRoleAuditReference(ctx context.Context, arg SetIdentityRoleAuditReferenceParams) error {
	_, err := q.db.Exec(ctx, setIdentityRoleAuditReference, arg.LastAuditReference, arg.ID)
	return err
}

const updateIdentityRole = `-- name: UpdateIdentityRole :execrows
UPDATE identity.role
SET name = $1,
    status = $2,
    aggregate_version = $3,
    updated_at = $4,
    last_audit_reference = $5
WHERE id = $6
  AND aggregate_version = $7
`

type UpdateIdentityRoleParams struct {
	Name                     string
	Status                   string
	NextAggregateVersion     int64
	UpdatedAt                pgtype.Timestamptz
	LastAuditReference       pgtype.UUID
	ID                       pgtype.UUID
	ExpectedAggregateVersion int64
}

func (q *Queries) UpdateIdentityRole(ctx context.Context, arg UpdateIdentityRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIdentityRole,
		arg.Name,
		arg.Status,
		arg.NextAggregateVersion,
		arg.UpdatedAt,
		arg.LastAuditReference,
		arg.ID,
		arg.ExpectedAggregateVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
