// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segregation_rule.sql

package identitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentitySegregationRule = `-- name: CreateIdentitySegregationRule :exec
INSERT INTO identity.segregation_rule (
    id, code, current_version, status, created_at, updated_at, last_audit_reference
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
`

type CreateIdentitySegregationRuleParams struct {
	ID                 pgtype.UUID
	Code               string
	CurrentVersion     int64
	Status             string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastAuditReference pgtype.UUID
}

func (q *Queries) CreateIdentitySegregationRule(ctx context.Context, arg CreateIdentitySegregationRuleParams) error {
	_, err := q.db.Exec(ctx, createIdentitySegregationRule,
		arg.ID,
		arg.Code,
		arg.CurrentVersion,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastAuditReference,
	)
	return err
}

const createIdentitySegregationRuleRevision = `-- name: CreateIdentitySegregationRuleRevision :exec
INSERT INTO identity.segregation_rule_revision (
    rule_id, revision_version, code, name, status, conflicting_permissions,
    enforcement_mode, scope_ids, amount_threshold, cooling_off_seconds,
    effective_from, effective_to, approval_request_id, approval_decision_id,
    approver_user_id, policy_version, decision_version, subject_version,
    candidate_fingerprint, audit_reference, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16,
    $17, $18, $19,
    $20, $21
)
`

type CreateIdentitySegregationRuleRevisionParams struct {
	RuleID                 pgtype.UUID
	RevisionVersion        int64
	Code                   string
	Name                   string
	Status                 string
	ConflictingPermissions []string
	EnforcementMode        string
	ScopeIds               []string
	AmountThreshold        pgtype.Numeric
	CoolingOffSeconds      int64
	EffectiveFrom          pgtype.Timestamptz
	EffectiveTo            pgtype.Timestamptz
	ApprovalRequestID      pgtype.UUID
	ApprovalDecisionID     pgtype.UUID
	ApproverUserID         pgtype.UUID
	PolicyVersion          string
	DecisionVersion        int64
	SubjectVersion         int64
	CandidateFingerprint   string
	AuditReference         pgtype.UUID
	CreatedAt              pgtype.Timestamptz
}

func (q *Queries) CreateIdentitySegregationRuleRevision(ctx context.Context, arg CreateIdentitySegregationRuleRevisionParams) error {
	_, err := q.db.Exec(ctx, createIdentitySegregationRuleRevision,
		arg.RuleID,
		arg.RevisionVersion,
		arg.Code,
		arg.Name,
		arg.Status,
		arg.ConflictingPermissions,
		arg.EnforcementMode,
		arg.ScopeIds,
		arg.AmountThreshold,
		arg.CoolingOffSeconds,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.ApprovalRequestID,
		arg.ApprovalDecisionID,
		arg.ApproverUserID,
		arg.PolicyVersion,
		arg.DecisionVersion,
		arg.SubjectVersion,
		arg.CandidateFingerprint,
		arg.AuditReference,
		arg.CreatedAt,
	)
	return err
}

const getCurrentIdentitySegregationRule = `-- name: GetCurrentIdentitySegregationRule :one
SELECT
    r.id,
    r.code,
    r.current_version,
    r.status,
    r.created_at,
    r.updated_at,
    r.last_audit_reference,
    rr.name,
    rr.conflicting_permissions,
    rr.enforcement_mode,
    rr.scope_ids,
    rr.amount_threshold,
    rr.cooling_off_seconds,
    rr.effective_from,
    rr.effective_to,
    rr.approval_request_id,
    rr.approval_decision_id,
    rr.approver_user_id,
    rr.policy_version,
    rr.decision_version,
    rr.subject_version,
    rr.candidate_fingerprint,
    rr.audit_reference,
    rr.created_at AS revision_created_at
FROM identity.segregation_rule AS r
JOIN identity.segregation_rule_revision AS rr
  ON rr.rule_id = r.id
 AND rr.revision_version = r.current_version
WHERE r.id = $1
`

type GetCurrentIdentitySegregationRuleRow struct {
	ID                     pgtype.UUID
	Code                   string
	CurrentVersion         int64
	Status                 string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	LastAuditReference     pgtype.UUID
	Name                   string
	ConflictingPermissions []string
	EnforcementMode        string
	ScopeIds               []string
	AmountThreshold        pgtype.Numeric
	CoolingOffSeconds      int64
	EffectiveFrom          pgtype.Timestamptz
	EffectiveTo            pgtype.Timestamptz
	ApprovalRequestID      pgtype.UUID
	ApprovalDecisionID     pgtype.UUID
	ApproverUserID         pgtype.UUID
	PolicyVersion          string
	DecisionVersion        int64
	SubjectVersion         int64
	CandidateFingerprint   string
	AuditReference         pgtype.UUID
	RevisionCreatedAt      pgtype.Timestamptz
}

func (q *Queries) GetCurrentIdentitySegregationRule(ctx context.Context, id pgtype.UUID) (GetCurrentIdentitySegregationRuleRow, error) {
	row := q.db.QueryRow(ctx, getCurrentIdentitySegregationRule, id)
	var i GetCurrentIdentitySegregationRuleRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CurrentVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAuditReference,
		&i.Name,
		&i.ConflictingPermissions,
		&i.EnforcementMode,
		&i.ScopeIds,
		&i.AmountThreshold,
		&i.CoolingOffSeconds,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.ApprovalRequestID,
		&i.ApprovalDecisionID,
		&i.ApproverUserID,
		&i.PolicyVersion,
		&i.DecisionVersion,
		&i.SubjectVersion,
		&i.CandidateFingerprint,
		&i.AuditReference,
		&i.RevisionCreatedAt,
	)
	return i, err
}

const listCurrentIdentitySegregationRules = `-- name: ListCurrentIdentitySegregationRules :many
SELECT
    r.id,
    r.code,
    r.current_version,
    r.status,
    r.created_at,
    r.updated_at,
    r.last_audit_reference,
    rr.name,
    rr.conflicting_permissions,
    rr.enforcement_mode,
    rr.scope_ids,
    rr.amount_threshold,
    rr.cooling_off_seconds,
    rr.effective_from,
    rr.effective_to,
    rr.approval_request_id,
    rr.approval_decision_id,
    rr.approver_user_id,
    rr.policy_version,
    rr.decision_version,
    rr.subject_version,
    rr.candidate_fingerprint,
    rr.audit_reference,
    rr.created_at AS revision_created_at
FROM identity.segregation_rule AS r
JOIN identity.segregation_rule_revision AS rr
  ON rr.rule_id = r.id
 AND rr.revision_version = r.current_version
ORDER BY r.code
`

type ListCurrentIdentitySegregationRulesRow struct {
	ID                     pgtype.UUID
	Code                   string
	CurrentVersion         int64
	Status                 string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	LastAuditReference     pgtype.UUID
	Name                   string
	ConflictingPermissions []string
	EnforcementMode        string
	ScopeIds               []string
	AmountThreshold        pgtype.Numeric
	CoolingOffSeconds      int64
	EffectiveFrom          pgtype.Timestamptz
	EffectiveTo            pgtype.Timestamptz
	ApprovalRequestID      pgtype.UUID
	ApprovalDecisionID     pgtype.UUID
	ApproverUserID         pgtype.UUID
	PolicyVersion          string
	DecisionVersion        int64
	SubjectVersion         int64
	CandidateFingerprint   string
	AuditReference         pgtype.UUID
	RevisionCreatedAt      pgtype.Timestamptz
}

func (q *Queries) ListCurrentIdentitySegregationRules(ctx context.Context) ([]ListCurrentIdentitySegregationRulesRow, error) {
	rows, err := q.db.Query(ctx, listCurrentIdentitySegregationRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentIdentitySegregationRulesRow
	for rows.Next() {
		var i ListCurrentIdentitySegregationRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CurrentVersion,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAuditReference,
			&i.Name,
			&i.ConflictingPermissions,
			&i.EnforcementMode,
			&i.ScopeIds,
			&i.AmountThreshold,
			&i.CoolingOffSeconds,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.ApprovalRequestID,
			&i.ApprovalDecisionID,
			&i.ApproverUserID,
			&i.PolicyVersion,
			&i.DecisionVersion,
			&i.SubjectVersion,
			&i.CandidateFingerprint,
			&i.AuditReference,
			&i.RevisionCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIdentitySegregationRuleAuditReference = `-- name: SetIdentitySegregationRuleAuditReference :exec
UPDATE identity.segregation_rule
SET last_audit_reference = $1
WHERE id = $2
`

type SetIdentitySegregationRuleAuditReferenceParams struct {
	LastAuditReference pgtype.UUID
	ID                 pgtype.UUID
}

func (q *Queries) SetIdentitySegregationRuleAuditReference(ctx context.Context, arg SetIdentitySegregationRuleAuditReferenceParams) error {
	_, err := q.db.Exec(ctx, setIdentitySegregationRuleAuditReference, arg.LastAuditReference, arg.ID)
	return err
}

const updateIdentitySegregationRule = `-- name: UpdateIdentitySegregationRule :execrows
UPDATE identity.segregation_rule
SET code = $1,
    current_version = $2,
    status = $3,
    updated_at = $4,
    last_audit_reference = $5
WHERE id = $6
  AND current_version = $7
`

type UpdateIdentitySegregationRuleParams struct {
	Code                   string
	NextCurrentVersion     int64
	Status                 string
	UpdatedAt              pgtype.Timestamptz
	LastAuditReference     pgtype.UUID
	ID                     pgtype.UUID
	ExpectedCurrentVersion int64
}

func (q *Queries) UpdateIdentitySegregationRule(ctx context.Context, arg UpdateIdentitySegregationRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIdentitySegregationRule,
		arg.Code,
		arg.NextCurrentVersion,
		arg.Status,
		arg.UpdatedAt,
		arg.LastAuditReference,
		arg.ID,
		arg.ExpectedCurrentVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
