// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package identitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentityUser = `-- name: CreateIdentityUser :exec
INSERT INTO identity.user_account (
    id,
    authentication_subject_oid,
    authentication_subject_tid,
    authentication_subject_sub,
    status,
    aggregate_version,
    created_at,
    updated_at,
    last_audit_reference
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type CreateIdentityUserParams struct {
	ID                       pgtype.UUID
	AuthenticationSubjectOid string
	AuthenticationSubjectTid string
	AuthenticationSubjectSub string
	Status                   string
	AggregateVersion         int64
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	LastAuditReference       pgtype.UUID
}

func (q *Queries) CreateIdentityUser(ctx context.Context, arg CreateIdentityUserParams) error {
	_, err := q.db.Exec(ctx, createIdentityUser,
		arg.ID,
		arg.AuthenticationSubjectOid,
		arg.AuthenticationSubjectTid,
		arg.AuthenticationSubjectSub,
		arg.Status,
		arg.AggregateVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastAuditReference,
	)
	return err
}

const createIdentityUserRoleAssignment = `-- name: CreateIdentityUserRoleAssignment :exec
INSERT INTO identity.user_role_assignment (user_id, role_id)
VALUES ($1, $2)
`

type CreateIdentityUserRoleAssignmentParams struct {
	UserID pgtype.UUID
	RoleID pgtype.UUID
}

func (q *Queries) CreateIdentityUserRoleAssignment(ctx context.Context, arg CreateIdentityUserRoleAssignmentParams) error {
	_, err := q.db.Exec(ctx, createIdentityUserRoleAssignment, arg.UserID, arg.RoleID)
	return err
}

const createIdentityUserRoleAssignmentScope = `-- name: CreateIdentityUserRoleAssignmentScope :exec
INSERT INTO identity.user_role_assignment_scope (user_id, role_id, scope_id)
VALUES ($1, $2, $3)
`

type CreateIdentityUserRoleAssignmentScopeParams struct {
	UserID  pgtype.UUID
	RoleID  pgtype.UUID
	ScopeID string
}

func (q *Queries) CreateIdentityUserRoleAssignmentScope(ctx context.Context, arg CreateIdentityUserRoleAssignmentScopeParams) error {
	_, err := q.db.Exec(ctx, createIdentityUserRoleAssignmentScope, arg.UserID, arg.RoleID, arg.ScopeID)
	return err
}

const deleteIdentityUserAssignments = `-- name: DeleteIdentityUserAssignments :exec
DELETE FROM identity.user_role_assignment
WHERE user_id = $1
`

func (q *Queries) DeleteIdentityUserAssignments(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIdentityUserAssignments, userID)
	return err
}

const findIdentityUserBySubject = `-- name: FindIdentityUserBySubject :one
SELECT
    id,
    authentication_subject_oid,
    authentication_subject_tid,
    authentication_subject_sub,
    status,
    aggregate_version,
    created_at,
    updated_at,
    last_audit_reference
FROM identity.user_account
WHERE authentication_subject_oid = $1
  AND authentication_subject_tid = $2
  AND authentication_subject_sub = $3
`

type FindIdentityUserBySubjectParams struct {
	AuthenticationSubjectOid string
	AuthenticationSubjectTid string
	AuthenticationSubjectSub string
}

func (q *Queries) FindIdentityUserBySubject(ctx context.Context, arg FindIdentityUserBySubjectParams) (IdentityUserAccount, error) {
	row := q.db.QueryRow(ctx, findIdentityUserBySubject, arg.AuthenticationSubjectOid, arg.AuthenticationSubjectTid, arg.AuthenticationSubjectSub)
	var i IdentityUserAccount
	err := row.Scan(
		&i.ID,
		&i.AuthenticationSubjectOid,
		&i.AuthenticationSubjectTid,
		&i.AuthenticationSubjectSub,
		&i.Status,
		&i.AggregateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAuditReference,
	)
	return i, err
}

const getIdentityUser = `-- name: GetIdentityUser :one
SELECT
    id,
    authentication_subject_oid,
    authentication_subject_tid,
    authentication_subject_sub,
    status,
    aggregate_version,
    created_at,
    updated_at,
    last_audit_reference
FROM identity.user_account
WHERE id = $1
`

func (q *Queries) GetIdentityUser(ctx context.Context, id pgtype.UUID) (IdentityUserAccount, error) {
	row := q.db.QueryRow(ctx, getIdentityUser, id)
	var i IdentityUserAccount
	err := row.Scan(
		&i.ID,
		&i.AuthenticationSubjectOid,
		&i.AuthenticationSubjectTid,
		&i.AuthenticationSubjectSub,
		&i.Status,
		&i.AggregateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAuditReference,
	)
	return i, err
}

const listIdentityUserRoleAssignments = `-- name: ListIdentityUserRoleAssignments :many
SELECT
    user_id,
    role_id,
    scope_id
FROM identity.user_role_assignment_scope
WHERE user_id = $1
ORDER BY role_id, scope_id
`

func (q *Queries) ListIdentityUserRoleAssignments(ctx context.Context, userID pgtype.UUID) ([]IdentityUserRoleAssignmentScope, error) {
	rows, err := q.db.Query(ctx, listIdentityUserRoleAssignments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityUserRoleAssignmentScope
	for rows.Next() {
		var i IdentityUserRoleAssignmentScope
		if err := rows.Scan(&i.UserID, &i.RoleID, &i.ScopeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentityUsers = `-- name: ListIdentityUsers :many
SELECT
    id,
    authentication_subject_oid,
    authentication_subject_tid,
    authentication_subject_sub,
    status,
    aggregate_version,
    created_at,
    updated_at,
    last_audit_reference
FROM identity.user_account
ORDER BY id
`

func (q *Queries) ListIdentityUsers(ctx context.Context) ([]IdentityUserAccount, error) {
	rows, err := q.db.Query(ctx, listIdentityUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityUserAccount
	for rows.Next() {
		var i IdentityUserAccount
		if err := rows.Scan(
			&i.ID,
			&i.AuthenticationSubjectOid,
			&i.AuthenticationSubjectTid,
			&i.AuthenticationSubjectSub,
			&i.Status,
			&i.AggregateVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAuditReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIdentityUserAuditReference = `-- name: SetIdentityUserAuditReference :exec
UPDATE identity.user_account
SET last_audit_reference = $1
WHERE id = $2
`

type SetIdentityUserAuditReferenceParams struct {
	LastAuditReference pgtype.UUID
	ID                 pgtype.UUID
}

func (q *Queries) SetIdentityUserAuditReference(ctx context.Context, arg SetIdentityUserAuditReferenceParams) error {
	_, err := q.db.Exec(ctx, setIdentityUserAuditReference, arg.LastAuditReference, arg.ID)
	return err
}

const updateIdentityUser = `-- name: UpdateIdentityUser :execrows
UPDATE identity.user_account
SET status = $1,
    aggregate_version = $2,
    updated_at = $3,
    last_audit_reference = $4
WHERE id = $5
  AND aggregate_version = $6
`

type UpdateIdentityUserParams struct {
	Status                   string
	NextAggregateVersion     int64
	UpdatedAt                pgtype.Timestamptz
	LastAuditReference       pgtype.UUID
	ID                       pgtype.UUID
	ExpectedAggregateVersion int64
}

func (q *Queries) UpdateIdentityUser(ctx context.Context, arg UpdateIdentityUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIdentityUser,
		arg.Status,
		arg.NextAggregateVersion,
		arg.UpdatedAt,
		arg.LastAuditReference,
		arg.ID,
		arg.ExpectedAggregateVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
