// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integration_outbox.sql

package platformdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueOutbox = `-- name: ClaimDueOutbox :many
WITH claim AS (
    SELECT outbox_id
    FROM integration.outbox
    WHERE established_at IS NULL
      AND available_at <= clock_timestamp()
      AND (claimed_until IS NULL OR claimed_until < clock_timestamp())
    ORDER BY available_at, outbox_id
    FOR UPDATE SKIP LOCKED
    LIMIT $3
)
UPDATE integration.outbox AS outbox
SET claimed_until = clock_timestamp() + $1::interval,
    claim_owner = $2,
    attempt_count = outbox.attempt_count + 1
FROM claim
WHERE outbox.outbox_id = claim.outbox_id
RETURNING outbox.outbox_id, outbox.event_type, outbox.event_version, outbox.source_context, outbox.aggregate_id, outbox.aggregate_version, outbox.accounting_scope_id, outbox.correlation_id, outbox.causation_id, outbox.payload, outbox.payload_fingerprint, outbox.available_at, outbox.claimed_until, outbox.claim_owner, outbox.attempt_count, outbox.established_at, outbox.last_error_code, outbox.created_at, outbox.occurred_at, outbox.data_classification
`

type ClaimDueOutboxParams struct {
	LeaseDuration pgtype.Interval
	ClaimOwner    pgtype.Text
	BatchSize     int32
}

func (q *Queries) ClaimDueOutbox(ctx context.Context, arg ClaimDueOutboxParams) ([]IntegrationOutbox, error) {
	rows, err := q.db.Query(ctx, claimDueOutbox, arg.LeaseDuration, arg.ClaimOwner, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationOutbox
	for rows.Next() {
		var i IntegrationOutbox
		if err := rows.Scan(
			&i.OutboxID,
			&i.EventType,
			&i.EventVersion,
			&i.SourceContext,
			&i.AggregateID,
			&i.AggregateVersion,
			&i.AccountingScopeID,
			&i.CorrelationID,
			&i.CausationID,
			&i.Payload,
			&i.PayloadFingerprint,
			&i.AvailableAt,
			&i.ClaimedUntil,
			&i.ClaimOwner,
			&i.AttemptCount,
			&i.EstablishedAt,
			&i.LastErrorCode,
			&i.CreatedAt,
			&i.OccurredAt,
			&i.DataClassification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutboxBySourceIdentity = `-- name: GetOutboxBySourceIdentity :one
SELECT outbox_id, event_type, event_version, source_context, aggregate_id, aggregate_version, accounting_scope_id, correlation_id, causation_id, payload, payload_fingerprint, available_at, claimed_until, claim_owner, attempt_count, established_at, last_error_code, created_at, occurred_at, data_classification
FROM integration.outbox
WHERE source_context = $1
  AND aggregate_id = $2
  AND aggregate_version = $3
  AND event_type = $4
`

type GetOutboxBySourceIdentityParams struct {
	SourceContext    string
	AggregateID      pgtype.UUID
	AggregateVersion int64
	EventType        string
}

func (q *Queries) GetOutboxBySourceIdentity(ctx context.Context, arg GetOutboxBySourceIdentityParams) (IntegrationOutbox, error) {
	row := q.db.QueryRow(ctx, getOutboxBySourceIdentity,
		arg.SourceContext,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.EventType,
	)
	var i IntegrationOutbox
	err := row.Scan(
		&i.OutboxID,
		&i.EventType,
		&i.EventVersion,
		&i.SourceContext,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.AccountingScopeID,
		&i.CorrelationID,
		&i.CausationID,
		&i.Payload,
		&i.PayloadFingerprint,
		&i.AvailableAt,
		&i.ClaimedUntil,
		&i.ClaimOwner,
		&i.AttemptCount,
		&i.EstablishedAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.OccurredAt,
		&i.DataClassification,
	)
	return i, err
}

const insertOutbox = `-- name: InsertOutbox :one
INSERT INTO integration.outbox (
    outbox_id,
    event_type,
    event_version,
    occurred_at,
    source_context,
    aggregate_id,
    aggregate_version,
    accounting_scope_id,
    correlation_id,
    causation_id,
    payload,
    payload_fingerprint,
    data_classification,
    available_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11::jsonb,
    $12,
    $13,
    $14
)
RETURNING outbox_id, event_type, event_version, source_context, aggregate_id, aggregate_version, accounting_scope_id, correlation_id, causation_id, payload, payload_fingerprint, available_at, claimed_until, claim_owner, attempt_count, established_at, last_error_code, created_at, occurred_at, data_classification
`

type InsertOutboxParams struct {
	OutboxID           pgtype.UUID
	EventType          string
	EventVersion       int32
	OccurredAt         pgtype.Timestamptz
	SourceContext      string
	AggregateID        pgtype.UUID
	AggregateVersion   int64
	AccountingScopeID  pgtype.UUID
	CorrelationID      pgtype.UUID
	CausationID        pgtype.UUID
	Payload            []byte
	PayloadFingerprint string
	DataClassification string
	AvailableAt        pgtype.Timestamptz
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) (IntegrationOutbox, error) {
	row := q.db.QueryRow(ctx, insertOutbox,
		arg.OutboxID,
		arg.EventType,
		arg.EventVersion,
		arg.OccurredAt,
		arg.SourceContext,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.AccountingScopeID,
		arg.CorrelationID,
		arg.CausationID,
		arg.Payload,
		arg.PayloadFingerprint,
		arg.DataClassification,
		arg.AvailableAt,
	)
	var i IntegrationOutbox
	err := row.Scan(
		&i.OutboxID,
		&i.EventType,
		&i.EventVersion,
		&i.SourceContext,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.AccountingScopeID,
		&i.CorrelationID,
		&i.CausationID,
		&i.Payload,
		&i.PayloadFingerprint,
		&i.AvailableAt,
		&i.ClaimedUntil,
		&i.ClaimOwner,
		&i.AttemptCount,
		&i.EstablishedAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.OccurredAt,
		&i.DataClassification,
	)
	return i, err
}

const listExpiredOutbox = `-- name: ListExpiredOutbox :many
SELECT outbox_id, event_type, event_version, source_context, aggregate_id, aggregate_version, accounting_scope_id, correlation_id, causation_id, payload, payload_fingerprint, available_at, claimed_until, claim_owner, attempt_count, established_at, last_error_code, created_at, occurred_at, data_classification
FROM integration.outbox
WHERE established_at IS NULL
  AND claimed_until IS NOT NULL
  AND claimed_until < clock_timestamp()
ORDER BY claimed_until, outbox_id
LIMIT $1
`

func (q *Queries) ListExpiredOutbox(ctx context.Context, maxRows int32) ([]IntegrationOutbox, error) {
	rows, err := q.db.Query(ctx, listExpiredOutbox, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationOutbox
	for rows.Next() {
		var i IntegrationOutbox
		if err := rows.Scan(
			&i.OutboxID,
			&i.EventType,
			&i.EventVersion,
			&i.SourceContext,
			&i.AggregateID,
			&i.AggregateVersion,
			&i.AccountingScopeID,
			&i.CorrelationID,
			&i.CausationID,
			&i.Payload,
			&i.PayloadFingerprint,
			&i.AvailableAt,
			&i.ClaimedUntil,
			&i.ClaimOwner,
			&i.AttemptCount,
			&i.EstablishedAt,
			&i.LastErrorCode,
			&i.CreatedAt,
			&i.OccurredAt,
			&i.DataClassification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
