// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integration_inbox.sql

package platformdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInboxByIdentity = `-- name: GetInboxByIdentity :one
SELECT consumer_name, message_id, message_fingerprint, state, result_reference, first_received_at, established_at
FROM integration.inbox
WHERE consumer_name = $1
  AND message_id = $2
`

type GetInboxByIdentityParams struct {
	ConsumerName string
	MessageID    pgtype.UUID
}

func (q *Queries) GetInboxByIdentity(ctx context.Context, arg GetInboxByIdentityParams) (IntegrationInbox, error) {
	row := q.db.QueryRow(ctx, getInboxByIdentity, arg.ConsumerName, arg.MessageID)
	var i IntegrationInbox
	err := row.Scan(
		&i.ConsumerName,
		&i.MessageID,
		&i.MessageFingerprint,
		&i.State,
		&i.ResultReference,
		&i.FirstReceivedAt,
		&i.EstablishedAt,
	)
	return i, err
}

const insertInbox = `-- name: InsertInbox :one
INSERT INTO integration.inbox (
    consumer_name,
    message_id,
    message_fingerprint,
    state,
    result_reference,
    established_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::jsonb,
    $6
)
RETURNING consumer_name, message_id, message_fingerprint, state, result_reference, first_received_at, established_at
`

type InsertInboxParams struct {
	ConsumerName       string
	MessageID          pgtype.UUID
	MessageFingerprint string
	State              string
	ResultReference    []byte
	EstablishedAt      pgtype.Timestamptz
}

func (q *Queries) InsertInbox(ctx context.Context, arg InsertInboxParams) (IntegrationInbox, error) {
	row := q.db.QueryRow(ctx, insertInbox,
		arg.ConsumerName,
		arg.MessageID,
		arg.MessageFingerprint,
		arg.State,
		arg.ResultReference,
		arg.EstablishedAt,
	)
	var i IntegrationInbox
	err := row.Scan(
		&i.ConsumerName,
		&i.MessageID,
		&i.MessageFingerprint,
		&i.State,
		&i.ResultReference,
		&i.FirstReceivedAt,
		&i.EstablishedAt,
	)
	return i, err
}

const listInboxForReconciliation = `-- name: ListInboxForReconciliation :many
SELECT consumer_name, message_id, message_fingerprint, state, result_reference, first_received_at, established_at
FROM integration.inbox
WHERE state IN ('processing', 'failed')
ORDER BY first_received_at, consumer_name, message_id
LIMIT $1
`

func (q *Queries) ListInboxForReconciliation(ctx context.Context, maxRows int32) ([]IntegrationInbox, error) {
	rows, err := q.db.Query(ctx, listInboxForReconciliation, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationInbox
	for rows.Next() {
		var i IntegrationInbox
		if err := rows.Scan(
			&i.ConsumerName,
			&i.MessageID,
			&i.MessageFingerprint,
			&i.State,
			&i.ResultReference,
			&i.FirstReceivedAt,
			&i.EstablishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
