// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: local_seed_manifest.sql

package platformdb

import (
	"context"
)

const getLocalSeedManifestChecksum = `-- name: GetLocalSeedManifestChecksum :one
SELECT checksum
FROM platform.local_seed_manifest
WHERE seed_name = $1
  AND seed_version = $2
`

type GetLocalSeedManifestChecksumParams struct {
	SeedName    string
	SeedVersion int64
}

func (q *Queries) GetLocalSeedManifestChecksum(ctx context.Context, arg GetLocalSeedManifestChecksumParams) (string, error) {
	row := q.db.QueryRow(ctx, getLocalSeedManifestChecksum, arg.SeedName, arg.SeedVersion)
	var checksum string
	err := row.Scan(&checksum)
	return checksum, err
}
