// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package platformdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PlatformLocalSeedManifest struct {
	SeedName    string
	SeedVersion int64
	Checksum    string
	AppliedAt   pgtype.Timestamptz
}
