// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package platformdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PlatformIdempotencyRecord struct {
	ScopeKey             string
	IdempotencyKey       string
	CanonicalFingerprint string
	OperationID          string
	State                string
	ResultStatus         pgtype.Int4
	ResultBody           []byte
	AggregateID          pgtype.UUID
	ProcessID            pgtype.UUID
	OwnerToken           pgtype.UUID
	LeaseUntil           pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
}

type PlatformLocalSeedManifest struct {
	SeedName    string
	SeedVersion int64
	Checksum    string
	AppliedAt   pgtype.Timestamptz
}
